Repository Clinical-Genomics/scout, pull requests merged in 2021-09, with the labels that each got.

#2837 Make ClinVar classification more evident in cancer variant page
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/cancer-variant.html
  scout/server/blueprints/variant/templates/variant/components.html
  scout/server/blueprints/variant/templates/variant/variant.html
Labels: Customer Request, Easy

#2842 Do not open new browser tabs when downloading files
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
  scout/server/blueprints/cases/templates/cases/gene_panel.html
  scout/server/blueprints/cases/templates/cases/individuals_table.html
Labels: Easy, Bugfix

#2850 Reintroduce missing splice junctions button on variant page
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/buttons.html
  scout/server/blueprints/variant/templates/variant/cancer-variant.html
  scout/server/blueprints/variant/templates/variant/components.html
  scout/server/blueprints/variant/templates/variant/variant.html
Labels: Bugfix

#2840 Update representative gene - Partly fix #2835 and #2826
  CHANGELOG.md
  scout/server/blueprints/variant/controllers.py
  scout/server/blueprints/variant/templates/variant/cancer-variant.html
  scout/server/blueprints/variant/utils.py
  scout/server/blueprints/variants/controllers.py
Labels: Bugfix

#2846 Collect COSMIC IDs from CSQ field named COSMIC
  CHANGELOG.md
  scout/parse/variant/transcript.py
  tests/parse/test_parse_transcripts.py
Labels: Bugfix

#2855 Display validation status badge also for not Sanger-sequenced variants
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/utils.html
Labels: enhancement, Customer Request, Easy

#2874 Fixed broken scout load OMIM command
  CHANGELOG.md
  scout/commands/load/panel.py
Labels: Easy, Bugfix

#2893 Removed padding after punctuation in comments
  CHANGELOG.md
  scout/server/app.py
  scout/server/blueprints/cases/templates/cases/case_report.html
  scout/server/templates/utils.html
Labels: bug
