Repository Clinical-Genomics/scout, pull requests merged in 2021-04, with the labels that each got.

#2489 Single other causative
  CHANGELOG.md
  scout/adapter/mongo/variant.py
  scout/server/blueprints/variant/controllers.py
Labels: Bugfix, Easy

#2483 Populate variants filter chromosomes choices according to genome build of the case
  CHANGELOG.md
  scout/constants/__init__.py
  scout/server/blueprints/variants/controllers.py
  scout/server/blueprints/variants/forms.py
  scout/server/blueprints/variants/views.py
  tests/server/blueprints/variants/test_variants_controllers.py
Labels: Bugfix, Easy

#2486 Clinical genes fix - fix #2445
  CHANGELOG.md
  scout/adapter/mongo/case.py
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/templates/cases/gene_panel.html
  scout/server/blueprints/cases/views.py
  scout/server/blueprints/institutes/views.py
  scout/server/blueprints/variants/controllers.py
  scout/server/blueprints/variants/views.py
  tests/server/blueprints/cases/conftest.py
  tests/server/blueprints/cases/test_cases_controllers.py
  tests/server/blueprints/cases/test_cases_views.py
Labels: Bugfix, Refactor

#2504 Bugfix 2503
  CHANGELOG.md
  scout/server/blueprints/variants/templates/variants/utils.html
Labels: Bugfix, Easy

#2502 Fix tests for CADD score parsing functions
  CHANGELOG.md
  tests/parse/test_parse_deleteriousness.py
  tests/parse/test_parse_transcripts.py
  tests/parse/test_parse_variant.py
Labels: Easy

#2505 Codefactor hof
  CHANGELOG.md
  scout/adapter/mongo/case.py
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/views.py
  scout/server/blueprints/variants/views.py
  scout/server/utils.py
  tests/build/test_build_variant.py
  tests/commands/conftest.py
  tests/conftest.py
Labels: Refactor

#2487 Splice junctions view
  CHANGELOG.md
  scout/commands/update/individual.py
  scout/models/case/case.py
  scout/server/blueprints/alignviewers/controllers.py
  scout/server/blueprints/alignviewers/templates/alignviewers/igv_sashimi_viewer.html
  scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html
  scout/server/blueprints/alignviewers/templates/alignviewers/utils.html
  scout/server/blueprints/alignviewers/views.py
  scout/server/blueprints/variant/controllers.py
  scout/server/blueprints/variant/templates/variant/buttons.html
  scout/server/blueprints/variant/templates/variant/sv-variant.html
  scout/server/blueprints/variant/templates/variant/utils.html
  scout/server/blueprints/variant/templates/variant/variant.html
  tests/server/blueprints/alignviewers/test_alignviewers_controllers.py
  tests/server/blueprints/variant/test_variant_controllers.py
Labels: Intermediate, RNA-seq, enhancement

#2513 Open variant in a new window
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/utils.html
  scout/server/blueprints/variants/templates/variants/utils.html
  scout/server/blueprints/variants/templates/variants/variants.html
Labels: Easy, QualityOfLife

#2528 Document UPD
  CHANGELOG.md
  docs/README.md
  docs/admin-guide/containers/systemd.md
  docs/admin-guide/genes.md
  docs/blog/new-3.0.md
  docs/blog/new-3.5.md
  docs/blog/new-4.0.0.md
  docs/img/Chromograph_color_legend.png
  docs/user-guide/cases.md
  docs/user-guide/dashboard.md
  docs/user-guide/variants.md
  mkdocs.yml
Labels: docs

#2533 Safer case chromosome check when populating variants chromosome filter
  CHANGELOG.md
  scout/server/blueprints/variants/controllers.py
Labels: Bugfix

#2530 Fix: IGV settings look ugly on some variants (#2523)
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/utils.html
  scout/server/blueprints/variant/templates/variant/variant.html
Labels: Bugfix

#2535 Display mitochondrial and rare diseases coverage report in cases with missing track
  CHANGELOG.md
  scout/adapter/mongo/case.py
  scout/models/case/case.py
  scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
Labels: Bugfix

#2556 Update individual docs + tiny bugfix
  CHANGELOG.md
  docs/admin-guide/README.md
  docs/admin-guide/load-config.md
  docs/admin-guide/updating-individuals.md
  mkdocs.yml
  scout/commands/update/individual.py
Labels: Bugfix, Easy, docs

#2551 Refactor dashboard searches
  CHANGELOG.md
  scout/server/blueprints/dashboard/controllers.py
  scout/server/blueprints/dashboard/forms.py
  scout/server/blueprints/dashboard/templates/dashboard/dashboard_general.html
  scout/server/blueprints/dashboard/views.py
  tests/server/blueprints/dashboard/test_dashboard_controllers.py
Labels: Bugfix, Refactor

#2566 Upgrade igv.js to version 2.8.1
  CHANGELOG.md
  scout/adapter/mongo/hgnc.py
  scout/commands/load/panel.py
  scout/server/blueprints/alignviewers/controllers.py
  scout/server/blueprints/alignviewers/templates/alignviewers/utils.html
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/institutes/controllers.py
  scout/server/blueprints/institutes/forms.py
  tests/adapter/mongo/test_diagnosis_handler.py
  tests/adapter/mongo/test_matchmaker.py
  tests/adapter/mongo/test_variant_handling.py
  tests/load/test_load_variant.py
  tests/server/blueprints/alignviewers/test_alignviewers_controllers.py
  tests/server/blueprints/cases/test_cases_views.py
  tests/server/blueprints/institutes/test_institute_views.py
  tests/server/blueprints/managed_variants/test_managed_variants_views.py
  tests/utils/test_utils_matchmaker.py
Labels: Bugfix
