Repository Clinical-Genomics/scout, pull requests merged in 2021-08, with the labels that each got.

#2756 Do not convert dismissal keys to integers when bulk-dismissing variants
  CHANGELOG.md
  scout/server/blueprints/variants/controllers.py
  tests/server/blueprints/variants/test_variants_views.py
Labels: Easy, Bugfix

#2769 Fix Typo In Documentation
  CHANGELOG.md
  docs/admin-guide/indexes.md
Labels: Easy, docs, Bugfix

#2761 Fix institute settings page crash
  CHANGELOG.md
  scout/server/blueprints/institutes/templates/overview/utils.html
Labels: bug

#2765 Bugfix loquscrash2 210727 2nd try
  CHANGELOG.md
  scout/server/extensions/loqus_extension.py
  tests/server/extensions/test_execute_command.py
  tests/server/extensions/test_loqusdb_api_extension.py
  tests/server/extensions/test_loqusdb_exe_extension.py
Labels: Bugfix

#2777 Bug fix #2776
  CHANGELOG.md
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/views.py
Labels: Easy, Bugfix

#2707 Check disease resource files before updating OMIM (and dropping old terms)
  CHANGELOG.md
  scout/commands/update/disease.py
  scout/constants/__init__.py
  scout/constants/phenotype.py
  scout/load/setup.py
  tests/commands/update/test_update_disease_cmd.py
Labels: Bugfix

#2783 Fix docker-compose files
  CHANGELOG.md
  Dockerfile
  containers/development/docker-compose-chanjo-report.yml
  containers/development/docker-compose-matchmaker.yml
  docker-compose-dev.yml
  docker-compose.yml
  setup.py
Labels: Easy, Bugfix

#2713 Populate clinical assessments for case pinned, causative and partial c…
  CHANGELOG.md
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/templates/cases/case_sma.html
  scout/server/blueprints/cases/templates/cases/utils.html
  scout/server/blueprints/variants/controllers.py
  scout/server/blueprints/variants/templates/variants/cancer-variants.html
  scout/server/blueprints/variants/templates/variants/utils.html
Labels: Easy, Bugfix

#2778 Better control over MatchMaker matching nodes and results
  CHANGELOG.md
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/templates/cases/matchmaker.html
  scout/server/blueprints/cases/templates/cases/utils.html
  scout/server/blueprints/cases/views.py
Labels: Easy, Bugfix

#2803 Do not remove update genes command tempdir before resource files are parsed
  CHANGELOG.md
  scout/commands/update/genes.py
Labels: Easy, Bugfix

#2812 Restore ACMG classification history in a scrollable div
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/cancer-variant.html
  scout/server/blueprints/variant/templates/variant/components.html
  scout/server/blueprints/variant/templates/variant/variant.html
Labels: Easy, Bugfix

#2810 Avoid case reports triggering the loading spinner
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
  scout/server/blueprints/cases/templates/cases/gene_panel.html
  scout/server/blueprints/cases/templates/cases/individuals_table.html
  scout/server/blueprints/variants/static/form_scripts.js
  scout/server/blueprints/variants/templates/variants/cancer-variants.html
Labels: Easy, Bugfix

#2819 Fix STR variantS export
  CHANGELOG.md
  scout/server/blueprints/variants/controllers.py
  scout/server/blueprints/variants/static/form_scripts.js
  scout/server/blueprints/variants/views.py
  tests/server/blueprints/variants/test_variants_views.py
Labels: Easy, Bugfix

#2827 Fixes link to other causative variants on variant page
  CHANGELOG.md
  scout/adapter/mongo/variant.py
  scout/server/blueprints/variant/templates/variant/components.html
Labels: Bugfix
