Repository Clinical-Genomics/scout, pull requests merged in 2021-05, with the labels that each got.

#2395 Update variants list view layout for cancer cases
  CHANGELOG.md
  scout/build/variant/variant.py
  scout/server/blueprints/institutes/templates/overview/gene_variants.html
  scout/server/blueprints/variants/controllers.py
  scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html
  scout/server/blueprints/variants/templates/variants/cancer-variants.html
  scout/server/blueprints/variants/templates/variants/components.html
  scout/server/blueprints/variants/templates/variants/indicators.html
  scout/server/blueprints/variants/templates/variants/str-variants.html
  scout/server/blueprints/variants/templates/variants/sv-variants.html
  scout/server/blueprints/variants/templates/variants/utils.html
  scout/server/blueprints/variants/templates/variants/variants.html
  scout/server/blueprints/variants/views.py
  scout/server/templates/utils.html
Labels: Cancer

#2587 Remove parsing of case `genome_version`, since it's not used anywhere downstream
  CHANGELOG.md
  scout/adapter/mongo/case.py
  scout/build/case.py
  scout/models/case/case.py
  tests/conftest.py
Labels: Easy, QualityOfLife

#2349 Refactor LoqusDB settings parsing and introducing Loqus queries via REST API
  CHANGELOG.md
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/institutes/forms.py
  scout/server/blueprints/variant/controllers.py
  scout/server/config.py
  scout/server/extensions/loqus_extension.py
  scout/utils/scout_requests.py
  tests/server/extensions/conftest.py
  tests/server/extensions/test_execute_command.py
  tests/server/extensions/test_loqusdb_api_extension.py
  tests/server/extensions/test_loqusdb_exe_extension.py
  tests/server/extensions/test_loqusdb_extension.py
  tests/server/extensions/test_loqusdb_extension_init.py
  tests/utils/test_scout_requests.py
Labels: Refactor

#2464 Filter lock
  CHANGELOG.md
  README.md
  docs/user-guide/institutes.md
  docs/user-guide/pages.md
  docs/user-guide/variants.md
  scout/adapter/mongo/event.py
  scout/adapter/mongo/filter.py
  scout/constants/__init__.py
  scout/constants/case_tags.py
  scout/constants/filters.py
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/templates/cases/case_report.html
  scout/server/blueprints/institutes/controllers.py
  scout/server/blueprints/institutes/templates/overview/filters.html
  scout/server/blueprints/institutes/templates/overview/institute_sidebar.html
  scout/server/blueprints/institutes/views.py
  scout/server/blueprints/managed_variants/templates/managed_variants/managed_variants.html
  scout/server/blueprints/variants/controllers.py
  scout/server/blueprints/variants/forms.py
  scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html
  scout/server/blueprints/variants/templates/variants/cancer-variants.html
  scout/server/blueprints/variants/templates/variants/str-variants.html
  scout/server/blueprints/variants/templates/variants/sv-variants.html
  scout/server/blueprints/variants/templates/variants/utils.html
  scout/server/blueprints/variants/templates/variants/variants.html
  scout/server/blueprints/variants/views.py
  tests/adapter/conftest.py
  tests/adapter/mongo/test_event_handling.py
  tests/conftest.py
  tests/server/blueprints/institutes/test_institute_views.py
Labels: enhancement

#2573 Sort ClinVar submission variants and case data by ascending "Last Evaluated" date
  CHANGELOG.md
  scout/adapter/mongo/clinvar.py
  scout/server/blueprints/institutes/templates/overview/clinvar_submissions.html
  scout/server/blueprints/institutes/templates/overview/institute_sidebar.html
  tests/adapter/mongo/test_clinvar_handler.py
Labels: Customer Request, Easy

#2594 Filter cancer variants by "is in ClinVar" and "is in Cosmic"
  CHANGELOG.md
  scout/adapter/mongo/query.py
  scout/constants/query_terms.py
  scout/server/blueprints/variants/forms.py
  scout/server/blueprints/variants/templates/variants/utils.html
  tests/adapter/mongo/test_query.py
Labels: Cancer, Customer Request, Easy

#2467 Refactoring MatchMaker as a Scout extension
  CHANGELOG.md
  scout/adapter/mongo/matchmaker.py
  scout/server/app.py
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/templates/cases/case.html
  scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
  scout/server/blueprints/cases/templates/cases/matchmaker.html
  scout/server/blueprints/cases/templates/cases/utils.html
  scout/server/blueprints/cases/views.py
  scout/server/config.py
  scout/server/extensions/__init__.py
  scout/server/extensions/matchmaker_extension.py
  scout/utils/matchmaker.py
  scout/utils/scout_requests.py
  tests/parse/test_parse_match_matchmaker.py
  tests/parse/test_parse_matchmaker.py
  tests/server/blueprints/cases/test_cases_templates.py
  tests/server/blueprints/cases/test_cases_views.py
  tests/server/blueprints/cases/test_matchmaker_controllers.py
  tests/server/conftest.py
  tests/server/extensions/test_matchmaker_extension.py
  tests/utils/test_scout_requests.py
  tests/utils/test_utils_matchmaker.py
Labels: Refactor

#2583 Rewrite Config Documentation
  CHANGELOG.md
  docs/admin-guide/README.md
  docs/admin-guide/load-config.md
Labels: docs

#2629 Tiny change in the MatchMaker window
  CHANGELOG.md
  containers/development/docker-compose-matchmaker.yml
  scout/server/blueprints/cases/templates/cases/utils.html
Labels: Easy, Frontend

#2634 Fixed crash when gene hasnt a primary_transcript
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/tx_overview.html
Labels: bug

#2673 Case index
  CHANGELOG.md
  scout/constants/indexes.py
Labels: Bugfix

#2672 Fix splice junction tracks not centered over genes when variants are in gene build 37
  CHANGELOG.md
  scout/server/blueprints/alignviewers/controllers.py
  scout/server/blueprints/alignviewers/templates/alignviewers/igv_sashimi_viewer.html
  scout/utils/ensembl_rest_clients.py
  tests/conftest.py
  tests/server/blueprints/alignviewers/test_alignviewers_controllers.py
  tests/utils/test_ensembl_rest_clients.py
Labels: Bugfix
