Repository Clinical-Genomics/scout, pull requests merged in 2021-06, with the labels that each got.

#2682 Show a warning if case config file has missing panels, do not crash
  CHANGELOG.md
  scout/build/case.py
  scout/server/blueprints/variants/controllers.py
  tests/build/test_build_case.py
Labels: Easy, QualityOfLife

#2709 Expand list of refseq trancripts in ClinVar submission form to reflect those in variant tx overview
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/clinvar.html
Labels: Bugfix, Easy, Frontend, enhancement

#2537 Rework cancer variant view
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/utils.html
  scout/server/blueprints/variant/templates/variant/cancer-variant.html
  scout/server/blueprints/variant/templates/variant/components.html
  scout/server/blueprints/variant/templates/variant/sanger.html
  scout/server/blueprints/variant/templates/variant/variant.html
  scout/server/blueprints/variant/templates/variant/variant_details.html
  scout/server/blueprints/variant/views.py
  scout/server/blueprints/variants/templates/variants/cancer-variants.html
  scout/server/config.py
  tests/conftest.py
  tests/server/blueprints/variant/test_variant_views.py
Labels: Cancer, enhancement

#2715 A more compact case page
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/case.html
  scout/server/blueprints/cases/templates/cases/gene_panel.html
  scout/server/blueprints/cases/templates/cases/individuals_table.html
  scout/server/blueprints/cases/templates/cases/phenotype.html
  scout/server/blueprints/cases/templates/cases/utils.html
  scout/server/blueprints/cases/views.py
  scout/server/blueprints/managed_variants/templates/managed_variants/managed_variants.html
  scout/server/templates/utils.html
  tests/server/blueprints/cases/test_cases_utils.py
Labels: Frontend, QualityOfLife, Refactor
