Repository Clinical-Genomics/scout, pull requests merged in 2021-11, with the labels that each got.

#2953 Fix UCSC links coordinates for SV variants with start chrom != end chrom
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/utils.html
Labels: Bugfix

#2952 Fix human readable variants name in case page for SV variants with start chrom != end chrom
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/utils.html
Labels: Bugfix

#2832 Speed up SV variants - gene symbols dont need transcripts
  CHANGELOG.md
  scout/adapter/mongo/hgnc.py
  scout/commands/view/hgnc.py
  scout/export/exon.py
  scout/load/all.py
  scout/parse/matchmaker.py
  scout/server/blueprints/alignviewers/controllers.py
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/templates/cases/case_report.html
  scout/server/blueprints/institutes/controllers.py
  scout/server/blueprints/institutes/views.py
  scout/server/blueprints/variants/controllers.py
  tests/adapter/mongo/test_gene_handler.py
  tests/build/test_build_disease.py
  tests/build/test_build_hgnc_gene.py
  tests/build/test_build_hgnc_transcript.py
  tests/build/test_build_hpo.py
Labels: Refactor

#2962 Fixed deprecated code after the release of WTForms 3.0
  CHANGELOG.md
  requirements.txt
  scout/__version__.py
  scout/adapter/mongo/variant.py
  scout/demo/643594.coverage.bed
  scout/demo/643595.coverage.bed
  scout/demo/hgnc.min.bed
  scout/server/blueprints/cases/static/madeline.svg
  scout/server/blueprints/dashboard/forms.py
  scout/server/blueprints/institutes/controllers.py
  scout/server/blueprints/institutes/forms.py
  scout/server/blueprints/managed_variants/forms.py
  scout/server/blueprints/panels/forms.py
  scout/server/blueprints/variants/forms.py
Labels: Bugfix

#2968 Fix broken load case when case has no custom images
  CHANGELOG.md
  scout/adapter/mongo/case.py
Labels: Bugfix

#2910 Remove and/or restore removed gene panels from GUI
  CHANGELOG.md
  scout/adapter/mongo/panel.py
  scout/commands/view/panels.py
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/templates/cases/gene_panel.html
  scout/server/blueprints/panels/controllers.py
  scout/server/blueprints/panels/templates/panels/panel.html
  scout/server/blueprints/panels/templates/panels/panels.html
  scout/server/blueprints/panels/views.py
  scout/server/blueprints/variants/controllers.py
  scout/server/blueprints/variants/views.py
  tests/server/blueprints/panels/test_panels_views.py
  tests/server/blueprints/variants/test_variants_controllers.py
Labels: enhancement

#2983 Fix to cancer variants page crashing when default gene panel was deleted
  CHANGELOG.md
  scout/adapter/mongo/panel.py
Labels: Bugfix

#2986 Fix startswith typo in tx_overview function (variant controllers)
  CHANGELOG.md
  scout/server/blueprints/variant/controllers.py
Labels: Easy, Bugfix

#2981 Reduce complexity of panels endpoint by moving some code to the panels controllers
  CHANGELOG.md
  scout/server/blueprints/panels/controllers.py
  scout/server/blueprints/panels/views.py
Labels: Easy, Refactor

#2980 Update requirements to use flask-ldap3-login>=0.9.17 instead of freezing WTForm
  CHANGELOG.md
  requirements.txt
Labels: Easy

#2996 Fix removing old gene panels with no 'maintainer' key
  CHANGELOG.md
  scout/server/blueprints/panels/controllers.py
  scout/server/blueprints/panels/views.py
Labels: Bugfix

#2998 Avoid case page crash on Phenomizer queries timeout
  CHANGELOG.md
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/views.py
Labels: Easy, Bugfix
