Repository Clinical-Genomics/scout, pull requests merged in 2022-12, with the labels that each got.

#3688 Update status of a ClinVar submission with no name
  CHANGELOG.md
  scout/server/blueprints/clinvar/templates/clinvar_submissions.html
Labels: Easy

#3702 Align OMIM diagnoses with delete diagnosis button on case page
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/phenotype.html
Labels: Easy

#3709 Tests for API endpoints
  CHANGELOG.md
  tests/server/blueprints/api/test_api_views.py
Labels: Easy

#3714 Fix STR source link generation
  CHANGELOG.md
  scout/server/links.py
Labels: Bugfix

#3711 Avoid duplicate causatives and pinned variants
  CHANGELOG.md
  scout/adapter/mongo/variant_events.py
Labels: Easy, Bugfix

#3716 Only ACMG terms in ClinVar clinsig when user selects ACMG 2015 as assertion criteria
  CHANGELOG.md
  scout/constants/clinvar.py
  scout/server/blueprints/clinvar/form.py
  scout/server/blueprints/clinvar/templates/multistep_add_variant.html
  scout/server/blueprints/clinvar/views.py
Labels: Easy

#3720 Add spacing on Beacon and MME items on case sidebar
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
Labels: Easy, Frontend

#3727 Handle connection timeout when sending requests to external web services
  CHANGELOG.md
  scout/server/blueprints/clinvar/templates/multistep_add_variant.html
  scout/utils/scout_requests.py
  tests/utils/test_scout_requests.py
Labels: Bugfix

#3731 Validate all submissions regardless of their status
  CHANGELOG.md
  scout/server/blueprints/clinvar/templates/clinvar_submissions.html
Labels: Easy
