Repository Clinical-Genomics/scout, pull requests merged in 2022-10, with the labels that each got.

#3614 Fix phenomodels typeahead
  CHANGELOG.md
  scout/adapter/mongo/case.py
  scout/server/blueprints/institutes/templates/overview/phenomodel.html
  tests/commands/load/test_load_research_cmd.py
  tests/commands/update/test_update_case_cmd.py
Labels: Easy

#3618 Add Type of analysis on Validated and Causatives pages
  CHANGELOG.md
  scout/server/blueprints/institutes/templates/overview/cases.html
  scout/server/blueprints/institutes/templates/overview/utils.html
Labels: Easy

#3623 Fix #3620 - fix adding callers on load
  CHANGELOG.md
  scout/build/variant/variant.py
  scout/parse/variant/callers.py
Labels: bug, Easy

#3622 Fix missing preselected chromosome when editing a managed variant
  CHANGELOG.md
  scout/server/blueprints/managed_variants/templates/managed_variants/managed_variants.html
Labels: Easy

#3624 Prepopulate variant type and subtype when editing a managed var
  CHANGELOG.md
  scout/server/blueprints/managed_variants/templates/managed_variants/managed_variants.html
Labels: Easy

#3627 Updated clinical SVs igv.js track (dbVar) and added example of external track from trackhubregistry
  CHANGELOG.md
  scout/constants/igv_tracks.py
  scout/server/config.py
Labels: Easy

#3628 Fix typo in dbVar Clinvar track hg19
  CHANGELOG.md
  scout/constants/igv_tracks.py
Labels: Easy

#3635 Filter cases by submitted to ClinVar
  CHANGELOG.md
  scout/adapter/mongo/case.py
  scout/adapter/mongo/clinvar.py
  scout/server/blueprints/institutes/controllers.py
  scout/server/blueprints/institutes/forms.py
  scout/server/blueprints/institutes/templates/overview/cases.html
  tests/adapter/mongo/test_clinvar_handler.py
Labels: Easy

#3641 Loqus priv
  CHANGELOG.md
  scout/server/blueprints/institutes/controllers.py
Labels: Bugfix
