Repository Clinical-Genomics/scout, pull requests merged in 2022-06, with the labels that each got.

#3382 Fix variants' pagination after filter
  CHANGELOG.md
  scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html
  scout/server/blueprints/variants/templates/variants/utils.html
Labels: Bugfix

#3374 Fix Matchmaker delete, form layout and functionality
  CHANGELOG.md
  scout/adapter/mongo/user.py
  scout/server/blueprints/cases/templates/cases/utils.html
Labels: Bugfix

#3383 Check if alignment files were removed from server before displaying their link
  CHANGELOG.md
  scout/server/blueprints/variant/controllers.py
  scout/server/utils.py
  tests/server/blueprints/variant/test_variant_controllers.py
Labels: Bugfix

#3393 Fix alignment of low tumor purity badge in cancer case page
  CHANGELOG.md
  scout/demo/cancer.load_config.yaml
  scout/server/blueprints/cases/templates/cases/individuals_table.html
Labels: Easy

#3396 Fixed updating genes in build 37
  CHANGELOG.md
  scout/utils/ensembl_rest_clients.py
  tests/server/blueprints/alignviewers/test_alignviewers_controllers.py
  tests/server/blueprints/variant/test_variant_views.py
  tests/utils/test_ensembl_rest_clients.py
Labels: Bugfix

#3394 Represent different tumor samples as vials in cases page
  CHANGELOG.md
  scout/server/blueprints/institutes/templates/overview/cases.html
Labels: Easy, Frontend

#3403 Drop classification float
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/acmg.html
  scout/server/static/bs_styles.css
Labels: Bugfix

#3433 More compact and visible comments
  CHANGELOG.md
  scout/server/static/bs_styles.css
  scout/server/templates/utils.html
Labels: QualityOfLife, Frontend

#3432 Add panel-umi tag option
  CHANGELOG.md
  scout/constants/case_tags.py
  scout/demo/cancer.load_config.yaml
  scout/parse/models.py
Labels: enhancement, Cancer

#3431 Fix updating HPO tems
  CHANGELOG.md
  scout/parse/hpo_terms.py
Labels: Easy, Bugfix

#3438 Remove leading and trailing spaces from cases search in cases and dashboard
  CHANGELOG.md
  scout/server/blueprints/dashboard/controllers.py
  scout/server/blueprints/institutes/controllers.py
Labels: Easy, Bugfix

#3440 Fix visibility of PANEL-UMI tag in cases page
  CHANGELOG.md
  scout/server/blueprints/institutes/templates/overview/cases.html
Labels: Bugfix

#3338 Associate institutes with multiple loqusdb instances
  CHANGELOG.md
  scout/adapter/mongo/institute.py
  scout/commands/update/institute.py
  scout/server/blueprints/institutes/controllers.py
  scout/server/blueprints/institutes/templates/overview/utils.html
  scout/server/blueprints/variant/controllers.py
  scout/server/blueprints/variant/templates/variant/variant_details.html
  scout/server/extensions/loqus_extension.py
  tests/adapter/mongo/test_institute_handler.py
  tests/server/blueprints/variant/test_variant_controllers.py
  tests/server/conftest.py
Labels: enhancement

#3461 Fix align of elems on the beacon submission modal
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/utils.html
Labels: Easy, Frontend

#3470 Local archive date and count
  CHANGELOG.md
  scout/adapter/mongo/variant_loader.py
  scout/build/variant/variant.py
  scout/demo/643594.clinical.vcf.gz
  scout/demo/643594.clinical.vcf.gz.tbi
  scout/models/variant/variant.py
  scout/parse/variant/headers.py
  scout/parse/variant/variant.py
  scout/server/blueprints/variant/templates/variant/variant_details.html
  tests/parse/test_parse_headers.py
Labels: enhancement, epic task
