Repository Clinical-Genomics/scout, pull requests merged in 2022-09, with the labels that each got.

#3570 Fix #3568 - HPO SVs: fix one button, add another
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/gene_panel.html
  scout/server/blueprints/variants/controllers.py
  scout/server/blueprints/variants/templates/variants/utils.html
Labels: Easy, Bugfix

#3565 Specify a confidence threshold (green|amber|red) when loading PanelApp panels
  CHANGELOG.md
  docs/admin-guide/panelapp_panels.md
  scout/commands/load/panel.py
  scout/constants/__init__.py
  scout/constants/gene_tags.py
  scout/load/panel.py
  scout/parse/panel.py
Labels: Customer Request

#3578 Export Funct anno (all vars), cancer VAFs and COSMIC IDs (cancer vars) when downloading variants
  CHANGELOG.md
  scout/constants/__init__.py
  scout/constants/variants_export.py
  scout/server/blueprints/variants/controllers.py
  tests/server/blueprints/variants/test_variants_controllers.py
Labels: Customer Request

#3592 Round CADD and GnomAD values in variants export files
  CHANGELOG.md
  scout/server/blueprints/variants/controllers.py
Labels: Easy

#3594 Checkbox to show/hide removed gene panels from Panels page
  CHANGELOG.md
  scout/server/blueprints/panels/templates/panels/panels.html
Labels: Customer Request, Easy
