Repository Clinical-Genomics/scout, pull requests merged in 2022-02, with the labels that each got.

#3122 Export general report to PDF using PDFKit
  .github/workflows/tests_and_cov.yml
  CHANGELOG.md
  Dockerfile
  Dockerfile-server
  requirements.txt
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/templates/cases/case_report.html
  scout/server/blueprints/cases/views.py
  scout/server/utils.py
Labels: Refactor

#3120 Export cancer's Coverage and QC report with PDFKit
  CHANGELOG.md
  Dockerfile
  README.md
  scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
  scout/server/blueprints/cases/views.py
  scout/server/utils.py
  tests/server/blueprints/cases/test_cases_views.py
  tests/server/test_server_utils.py
Labels: Easy, Refactor, Bugfix

#3127 Show Swedac logo in portrait-oriented delivery report
  CHANGELOG.md
  scout/demo/delivery_report.html
  scout/server/blueprints/cases/views.py
Labels: Easy, Refactor, Bugfix

#3152 Test for report existence - Fix #3130
  CHANGELOG.md
  scout/server/app.py
  scout/server/blueprints/cases/templates/cases/case.html
  scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
  scout/server/blueprints/cases/views.py
  tests/server/blueprints/cases/test_cases_templates.py
Labels: Bugfix

#3151 Fix Matchmaker submission things as per paper review
  CHANGELOG.md
  README.md
  docs/admin-guide/README.md
  docs/admin-guide/matchmaker_exchange_integration.md
  docs/admin-guide/server.md
  docs/user-guide/cases.md
  mkdocs.yml
  scout/constants/case_tags.py
  scout/parse/matchmaker.py
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
  scout/server/blueprints/cases/templates/cases/matchmaker.html
  scout/server/blueprints/cases/templates/cases/utils.html
  scout/server/config.py
  tests/parse/test_parse_matchmaker.py
Labels: Customer Request, Bugfix

#3158 Fix unable to fetch libs during Docker build in GitHub actions
  .github/workflows/tests_and_cov.yml
  CHANGELOG.md
Labels: Easy, Bugfix

#3155 Remove null non-mandatory key/values when updating a case
  CHANGELOG.md
  scout/adapter/mongo/case.py
  scout/parse/case.py
  tests/adapter/mongo/test_matchmaker.py
Labels: Easy, Bugfix

#3154 Remove unused chromograph case keys
  CHANGELOG.md
  scout/adapter/mongo/case.py
  scout/build/case.py
Labels: Easy

#3164 Fixed managed variants search by description
  CHANGELOG.md
  scout/adapter/mongo/managed_variant.py
  scout/adapter/mongo/variant.py
  scout/server/blueprints/managed_variants/controllers.py
Labels: Easy, Bugfix

#3169 Slightly smaller and improved layout of content in case PDF report
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/case_report.html
  scout/server/blueprints/cases/views.py
  scout/server/templates/report_base.html
Labels: Easy, Frontend

#3168 Removed unused add_compounds param from variant controllers function
  CHANGELOG.md
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/variant/controllers.py
  scout/server/blueprints/variant/verification_controllers.py
  tests/server/blueprints/variant/test_variant_controllers.py
Labels: Easy

#3186 Panel id except
  CHANGELOG.md
  scout/adapter/mongo/panel.py
  scout/server/blueprints/panels/views.py
Labels: Easy, Bugfix

#3175 Fix #3174 - silence chr-coord if hgvs in clinvar export
  CHANGELOG.md
  scout/constants/__init__.py
  scout/constants/clinvar.py
  scout/parse/clinvar.py
Labels: Easy, Bugfix
