Repository Clinical-Genomics/scout, pull requests merged in 2022-03, with the labels that each got.

#3069 Make phenotype non-mandatory when assigning partial causatives
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/cancer-variant.html
  scout/server/blueprints/variant/templates/variant/sv-variant.html
  scout/server/blueprints/variant/templates/variant/utils.html
  scout/server/blueprints/variant/templates/variant/variant.html
  tests/server/blueprints/variant/test_variant_utils.py
Labels: Customer Request, Easy

#3176 Fix #3173 - ClinVar export prefer OMIM condition
  CHANGELOG.md
  scout/server/blueprints/variant/controllers.py
  scout/server/blueprints/variant/templates/variant/clinvar.html
  scout/server/blueprints/variant/templates/variant/sanger.html
  scout/server/blueprints/variant/templates/variant/sv-variant.html
  scout/server/blueprints/variant/views.py
Labels: Easy, Bugfix

#3198 Fixed parsing of old frequency obs
  CHANGELOG.md
  scout/build/variant/variant.py
  scout/models/variant/variant.py
  scout/parse/variant/variant.py
  scout/server/blueprints/variant/templates/variant/variant_details.html
  tests/parse/test_parse_variant.py
Labels: Bugfix

#3201 Filter out variants that are found only in unaffected individuals
  CHANGELOG.md
  scout/adapter/mongo/hgnc.py
  scout/adapter/mongo/query.py
  scout/constants/query_terms.py
  scout/server/blueprints/variants/controllers.py
  scout/server/blueprints/variants/forms.py
  scout/server/blueprints/variants/templates/variants/utils.html
  scout/server/blueprints/variants/templates/variants/variants.html
  tests/adapter/mongo/test_query.py
  tests/conftest.py
  tests/server/blueprints/variants/conftest.py
  tests/server/blueprints/variants/test_variants_views.py
Labels: enhancement

#3228 Fix mark partial causative
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/utils.html
  scout/server/blueprints/variant/templates/variant/utils.html
Labels: Bugfix

#3233 Test compound filter - Partially Fix #374
  CHANGELOG.md
  scout/constants/variant_tags.py
  scout/server/blueprints/variants/controllers.py
  scout/server/blueprints/variants/forms.py
  scout/server/blueprints/variants/templates/variants/utils.html
  scout/server/blueprints/variants/templates/variants/variants.html
  scout/server/blueprints/variants/views.py
  tests/adapter/mongo/test_query.py
  tests/server/blueprints/variants/test_variants_controllers.py
Labels: epic task

#3264 Fix IARC link
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/components.html
  scout/server/links.py
Labels: Easy, Bugfix

#3272 Remove flask-debugtoolbar that uses deprecated Jinja2 code
  CHANGELOG.md
  requirements.txt
  scout/server/app.py
  scout/server/extensions/__init__.py
Labels: Easy, Bugfix

#3269 Fix variant page crashing when OMIM terms are list of integers
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/utils.html
Labels: Easy, Bugfix

#3279 Freeze temporarily Werkzeug to v.2.0 to fix deprecated safe_str_cmp import
  CHANGELOG.md
  requirements.txt
Labels: Easy, Bugfix, blocking
