Repository Clinical-Genomics/scout, pull requests merged in 2023-06, with the labels that each got.

#3976 Improved Institute Settings layout
  CHANGELOG.md
  scout/server/blueprints/institutes/templates/overview/utils.html
Labels: Easy, Frontend

#3977 Fix gene variant hgvs
  CHANGELOG.md
  scout/server/app.py
  scout/server/blueprints/institutes/controllers.py
  scout/server/blueprints/institutes/templates/overview/gene_variants.html
  scout/server/blueprints/variants/templates/variants/components.html
  scout/server/blueprints/variants/templates/variants/variants.html
Labels: Easy

#3989 Clearer pop freq in variants list
  CHANGELOG.md
  scout/server/blueprints/variants/templates/variants/components.html
  scout/server/blueprints/variants/templates/variants/variants.html
Labels: Easy, QualityOfLife, Frontend

#3998 Include ClinVar variants into a scrollable div on Case page
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/clinvar.html
Labels: Customer Request, Easy, QualityOfLife, Frontend

#4006 Fix gunicorn workers booting by modifying Dockerfiles to use python bullseye
  CHANGELOG.md
  Dockerfile
  Dockerfile-server
Labels: Bugfix
