Repository Clinical-Genomics/scout, pull requests merged in 2023-01, with the labels that each got.

#3746 Fix adding case to a group without valid case name
  CHANGELOG.md
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/templates/cases/case.html
Labels: Easy, Bugfix

#3740 Dedicated data sharing col on cases page
  CHANGELOG.md
  scout/server/blueprints/institutes/templates/overview/cases.html
Labels: Easy

#3742 Modify OMIM download test to cover untested function
  CHANGELOG.md
  scout/commands/download/omim.py
  tests/commands/download/test_download_omim_cmd.py
Labels: Easy

#3741 Don't show custom tracks if user unselects them all
  CHANGELOG.md
  scout/server/blueprints/alignviewers/controllers.py
Labels: Easy

#3756 Fix #3755 - REViewer button on variant page
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/buttons.html
  scout/server/blueprints/variant/templates/variant/components.html
Labels: Easy, Frontend

#3765 Fix manual rank message
  CHANGELOG.md
  scout/server/blueprints/variant/views.py
Labels: Easy, QualityOfLife

#3773 Fix gene and functanno visibility on Causatives/Validated page
  CHANGELOG.md
  scout/server/blueprints/variants/templates/variants/components.html
Labels: Easy, Frontend

#3772 Fix causatives page
  CHANGELOG.md
  scout/adapter/mongo/variant.py
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/institutes/controllers.py
  tests/server/blueprints/variant/test_variant_controllers.py
Labels: Bugfix
