Repository Clinical-Genomics/scout, pull requests merged in 2023-02, with the labels that each got.

#3802 PanelApp Green Genes panel
  CHANGELOG.md
  scout/commands/update/base.py
  scout/commands/update/omim.py
  scout/commands/update/panelapp.py
  scout/load/panel.py
  tests/commands/update/test_update_panelapp_green.py
Labels: enhancement, Customer Request

#3803 Somatic matching classified
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/cancer-variant.html
  scout/server/blueprints/variant/templates/variant/components.html
  scout/server/blueprints/variants/templates/variants/cancer-variants.html
Labels: Easy, Bugfix, Frontend

#3809 Fix #3808 - VarSome link to hg19
  CHANGELOG.md
  scout/server/links.py
Labels: Bugfix

#3807 Fix managed vars filter
  CHANGELOG.md
  scout/server/blueprints/managed_variants/templates/managed_variants/managed_variants.html
Labels: Bugfix

#3819 Fix research vars counter
  CHANGELOG.md
  scout/server/blueprints/variants/views.py
Labels: Bugfix

#3816 Fix Beacon links to support variants in build 38
  CHANGELOG.md
  scout/server/links.py
  tests/server/test_links.py
Labels: Easy, Bugfix
