Repository Clinical-Genomics/scout, pull requests merged in 2023-10, with the labels that each got.

#4098 Truncate long HGVS ids on case page
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/utils.html
Labels: Easy, Bugfix

#4108 Fix potential missing protein name bug
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/utils.html
Labels: Easy, Bugfix

#4109 Simplify and possibly speed up case report
  CHANGELOG.md
  scout/adapter/mongo/event.py
  scout/constants/__init__.py
  scout/constants/case_tags.py
  scout/constants/variant_tags.py
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/views.py
Labels: Refactor

#4100 Reduce case view loading time by speeding up case retrieval in case_matching_causatives (maybe).
  CHANGELOG.md
  scout/adapter/mongo/variant.py
  scout/server/blueprints/cases/controllers.py
Labels: enhancement

#4122 Remove case diagnoses even when not found in db
  CHANGELOG.md
  scout/adapter/mongo/case_events.py
  scout/server/blueprints/cases/views.py
  tests/adapter/conftest.py
  tests/adapter/mongo/test_case_events.py
  tests/adapter/mongo/test_case_handling.py
  tests/adapter/mongo/test_diagnosis_handler.py
  tests/server/blueprints/cases/test_cases_views.py
Labels: Bugfix

#4123 Fix missing disease-associated HPO terms
  CHANGELOG.md
  scout/load/hpo.py
  scout/parse/hpo_mappings.py
Labels: Bugfix

#4126 unfreeze PyMongo
  CHANGELOG.md
  requirements.txt
  scout/adapter/mongo/base.py
  scout/adapter/mongo/variant_loader.py
Labels: Easy

#4130 Remove warnings and unused build_phenotype module
  CHANGELOG.md
  scout/build/__init__.py
  scout/build/disease.py
  scout/build/phenotype.py
Labels: Easy

#4134 Stricter genome build validation when loading case + missing tests
  CHANGELOG.md
  docs/admin-guide/loading-case.md
  scout/demo/643594.config.yaml
  scout/demo/643595.config.yaml
  scout/demo/cancer.load_config.yaml
  scout/demo/rnafusion.load_config.yaml
  scout/models/case/case_loading_models.py
  tests/conftest.py
  tests/parse/test_parse_case.py
Labels: Easy

#4137 Fix displaying custom case images loaded with scout version <= 4.71
  CHANGELOG.md
  scout/server/blueprints/cases/controllers.py
Labels: Easy, Bugfix

#4133 Improve readability of coordinates and variants size
  CHANGELOG.md
  scout/server/app.py
  scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html
  scout/server/blueprints/variants/templates/variants/mei-variants.html
  scout/server/blueprints/variants/templates/variants/str-variants.html
  scout/server/blueprints/variants/templates/variants/sv-variants.html
  tests/server/test_app.py
Labels: enhancement, Customer Request, Easy

#4144 Tentaive fix to server hanging
  CHANGELOG.md
  scout/adapter/mongo/variant.py
Labels: Bugfix

#4163 Fix genemap2 parsing
  CHANGELOG.md
  scout/parse/omim.py
Labels: Bugfix
