Repository Clinical-Genomics/scout, pull requests merged in 2023-12, with the labels that each got.

#4274 Fix extra chars on general report
  CHANGELOG.md
  scout/server/templates/report_base.html
Labels: Easy, QualityOfLife, Bugfix

#4275 Parse and show RNA fusion found_db key/values
  CHANGELOG.md
  scout/build/variant/variant.py
  scout/parse/variant/variant.py
  scout/server/blueprints/variants/templates/variants/fusion-variants.html
Labels: enhancement, Easy, Bugfix

#4284 Restore changelog format
  CHANGELOG.md
Labels: Easy, QualityOfLife

#4279 Fix Alamut link for MT variants in build 38
  CHANGELOG.md
  scout/server/links.py
Labels: Easy, Bugfix

#4127 Wtforms unfreeze
  CHANGELOG.md
  requirements.txt
  scout/adapter/mongo/event.py
  scout/adapter/mongo/filter.py
  scout/build/variant/variant.py
  scout/server/blueprints/clinvar/form.py
  scout/server/blueprints/variants/controllers.py
  scout/server/blueprints/variants/forms.py
  scout/server/blueprints/variants/templates/variants/utils.html
Labels: Refactor

#4292 Fix type of some RNA fusion variant keys
  CHANGELOG.md
  scout/parse/variant/variant.py
Labels: Easy, Bugfix

#4287 Fix removing of None key/values before saving parsed variants
  CHANGELOG.md
  scout/parse/variant/variant.py
  scout/utils/convert.py
Labels: Easy, Bugfix

#4289 Alamut indel links
  CHANGELOG.md
  scout/server/blueprints/genes/controllers.py
  scout/server/blueprints/variant/templates/variant/components.html
  scout/server/blueprints/variant/utils.py
  scout/server/links.py
  tests/server/test_links.py
Labels: Bugfix

#4282 Fix GT ref and alt depth parsing when values are 0
  CHANGELOG.md
  scout/parse/variant/genotype.py
  tests/conftest.py
  tests/parse/test_parse_genotype.py
Labels: Easy, Bugfix

#4302 Fix updating unexisting user crash
  CHANGELOG.md
  scout/commands/update/user.py
Labels: Easy, Bugfix

#4305 Unfreeze coloredlogs
  CHANGELOG.md
  requirements.txt
Labels: Easy
