Repository Clinical-Genomics/scout, pull requests merged in 2023-08, with the labels that each got.

#4026 Fix admin docs to run docker scout on Mac - Arm processor
  CHANGELOG.md
  docs/admin-guide/containers/container-deploy.md
Labels: Easy, docs

#4029 Fixed Weasyprint installation howto link
  CHANGELOG.md
  README.md
Labels: Easy, docs

#4053 Fix visualization of cancer variants where cancer case has no affected
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/variant_details.html
Labels: Easy, Bugfix

#3963 Refactor a couple of complex case related files
  CHANGELOG.md
  scout/adapter/mongo/case.py
  scout/server/blueprints/cases/controllers.py
Labels: QualityOfLife, Refactor
