Repository Clinical-Genomics/scout, pull requests merged in 2023-11, with the labels that each got.

#4191 Fix #4190 - GnomAD web service defaults to hg38
  CHANGELOG.md
  scout/server/links.py
Labels: bug

#4188 Mei hpo button
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/gene_panel.html
Labels: Easy, QualityOfLife

#4193 Clearer STRs on case general report
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/case_report.html
Labels: Easy

#4189 Fix #4182 - export managed variants from CLI
  CHANGELOG.md
  scout/adapter/mongo/managed_variant.py
  scout/commands/export/export_command.py
  scout/commands/export/utils.py
  scout/commands/export/variant.py
  scout/constants/indexes.py
  scout/export/variant.py
Labels: enhancement, Customer Request

#4200 Fix missing family name parsing
  CHANGELOG.md
  scout/models/case/case_loading_models.py
  tests/parse/test_parse_case.py
Labels: Easy, Bugfix

#4185 Fix #4131 again - more formatted long int and copy to clipboards
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/cancer-variant.html
  scout/server/blueprints/variant/templates/variant/components.html
  scout/server/blueprints/variant/templates/variant/sv-variant.html
  scout/server/blueprints/variant/templates/variant/utils.html
  scout/server/blueprints/variant/templates/variant/variant.html
Labels: Customer Request, QualityOfLife

#4212 Added Decipher button to SNV/MEI and str variant page
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/components.html
  scout/server/links.py
Labels: Customer Request, Easy

#4221 Add test and fixtures for RNA fusion case page
  CHANGELOG.md
  tests/conftest.py
  tests/server/blueprints/cases/test_cases_views.py
Labels: Easy

#4234 Fix saving mei filters
  CHANGELOG.md
  scout/adapter/mongo/filter.py
Labels: Easy, Bugfix

#4235 Audit filters specifics on case report
  CHANGELOG.md
  scout/adapter/mongo/filter.py
  scout/constants/__init__.py
  scout/constants/variant_tags.py
  scout/server/app.py
  scout/server/blueprints/cases/templates/cases/case_report.html
  scout/server/blueprints/variants/controllers.py
  tests/server/test_app.py
Labels: enhancement, Easy

#4240 Compound follow multi gene
  CHANGELOG.md
  scout/adapter/mongo/variant_loader.py
  scout/build/variant/genotype.py
  scout/server/blueprints/variants/controllers.py
Labels: Bugfix

#4246 Revert global styles and fix variant buttons style instead
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/components.html
  scout/server/static/bs_styles.css
Labels: Easy
