Repository Clinical-Genomics/scout, pull requests merged in 2024-04, with the labels that each got.

#4542 Fix #4541 - DUX4::IGH BALSAMIC SV caller tag
  CHANGELOG.md
  scout/constants/__init__.py
Labels: Easy

#4555 Fix cancer_rank_options typo in case report
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/case_report.html
Labels: Easy, Bugfix

#4553 Direct links to chanjo2 external app
  CHANGELOG.md
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/templates/cases/chanjo2_form.html
  scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
  scout/server/blueprints/cases/templates/cases/gene_panel.html
  scout/server/blueprints/cases/views.py
  scout/server/blueprints/panels/templates/panels/panel.html
  tests/server/blueprints/cases/test_cases_views.py
Labels: enhancement, Bugfix

#4569 Changed case report to display more info for fusion variants
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/case_report.html
  scout/server/blueprints/variants/templates/variants/components.html
  scout/server/blueprints/variants/templates/variants/fusion-variants.html
Labels: Customer Request, Easy

#4574 Pagination and nr HPO terms on Phenotypes page
  CHANGELOG.md
  scout/server/blueprints/phenotypes/templates/phenotypes/hpo_terms.html
Labels: enhancement, Easy, QualityOfLife

#4575 Fix link name on caseS page
  CHANGELOG.md
  scout/server/blueprints/institutes/templates/overview/cases.html
Labels: Easy, Bugfix

#4576 Block ClinVar submission of somatic variants, to reflect changes in ClinVar API
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/utils.html
Labels: Easy

#4587 Fix installation of wkhtmltopdf in GitHub action
  .github/workflows/tests_and_cov.yml
  CHANGELOG.md
Labels: Bugfix

#4589 Fix ClinVar form parsing to not include : in conditionType.id when condition is Orphanet
  CHANGELOG.md
  scout/constants/clinvar.py
Labels: Easy, Bugfix

#4583 Improved visibility of ClinVar form in dark mode
  CHANGELOG.md
  scout/server/blueprints/clinvar/templates/clinvar/multistep_add_variant.html
Labels: Easy, Bugfix, Frontend

#4592 Typehead diseases when query contains source substring
  CHANGELOG.md
  scout/adapter/mongo/disease_terms.py
Labels: Easy, QualityOfLife

#4593 Fix end coordinates in ClinVar for indels
  CHANGELOG.md
  scout/server/blueprints/clinvar/controllers.py
Labels: Easy, Bugfix

#4594 Stricter control over ClinVar condition IDs provided in ClinVar form
  CHANGELOG.md
  scout/server/blueprints/clinvar/templates/clinvar/multistep_add_variant.html
Labels: QualityOfLife
