Repository Clinical-Genomics/scout, pull requests merged in 2024-03, with the labels that each got.

#4474 Add button for displaying STR variants occurring in the dynamic HPO panel on case page
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/gene_panel.html
  scout/server/blueprints/variants/views.py
Labels: Customer Request, Easy

#4475 Reroute case no institute
  CHANGELOG.md
  scout/server/blueprints/cases/views.py
  tests/server/blueprints/cases/test_cases_views.py
Labels: enhancement

#4482 'Institutes to share cases with' select displays institute names and IDs
  CHANGELOG.md
  scout/server/blueprints/institutes/controllers.py
Labels: Customer Request, Easy

#4483 Fix #4480 - show ACMG VUS on general report
  CHANGELOG.md
  scout/adapter/mongo/event.py
  scout/server/blueprints/cases/controllers.py
Labels: Easy, Bugfix

#4493 Fix #4491 - case incidental finding tag
  CHANGELOG.md
  scout/constants/case_tags.py
Labels: enhancement, Easy

#4498 Fix bug exporting variants without rank score
  CHANGELOG.md
  scout/server/blueprints/variants/controllers.py
Labels: Easy, Bugfix

#4497 Display custom annotations also on cancer variant page
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/cancer-variant.html
  scout/server/blueprints/variant/templates/variant/sv-variant.html
  scout/server/blueprints/variant/templates/variant/utils.html
  scout/server/blueprints/variant/templates/variant/variant.html
Labels: Easy

#4508 Fix search for variants in genes present only in build 38 returning no results
  CHANGELOG.md
  scout/server/blueprints/variants/views.py
Labels: Easy, Bugfix

#4516 Provide a test for the chanjo2_coverage_report endpoint
  CHANGELOG.md
  tests/server/blueprints/cases/test_cases_views.py
Labels: Easy

#4518 Add link chanjo2 coverage report on gene panel page
  CHANGELOG.md
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/views.py
  scout/server/blueprints/panels/templates/panels/panel.html
  scout/server/blueprints/panels/views.py
Labels: enhancement, Easy

#4534 Link to chanjo2 genes overview on gene panel page
  CHANGELOG.md
  scout/server/blueprints/panels/templates/panels/panel.html
Labels: enhancement, Easy

#4536 Fix button size on HPO panel
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/gene_panel.html
Labels: Easy, Frontend
