Repository Clinical-Genomics/scout, pull requests merged in 2024-01, with the labels that each got.

#4310 Fix missing phenomodels icon
  CHANGELOG.md
  scout/server/blueprints/phenomodels/templates/phenomodels.html
Labels: Easy, Bugfix

#4312 Fixed missing cryptography lib error with Docker on ARM processor
  CHANGELOG.md
  docker-compose.yml
Labels: Easy, QualityOfLife

#4319 Validate custom image paths when a case is loaded
  CHANGELOG.md
  scout/models/case/case_loading_models.py
Labels: Easy

#4323 Fix #4322 - ClinVar submitters cleared with unpriv saving
  CHANGELOG.md
  scout/adapter/mongo/panel.py
  scout/server/blueprints/institutes/controllers.py
Labels: Bugfix

#4336 Fix None search as default case search in cases form
  CHANGELOG.md
  scout/server/blueprints/institutes/forms.py
Labels: Easy, Bugfix

#4337 Fix removing the same ClinVar variant from 2 different tabs
  CHANGELOG.md
  scout/adapter/mongo/clinvar.py
Labels: Bugfix

#4317 Fix missing genes, links and functional anno for fusion variants in causatives and verified pages
  CHANGELOG.md
  scout/server/blueprints/institutes/templates/overview/utils.html
  scout/server/blueprints/variants/templates/variants/components.html
  scout/server/blueprints/variants/templates/variants/fusion-variants.html
Labels: Bugfix

#4291 Remove dead functions and their tests
  CHANGELOG.md
  scout/adapter/mongo/case.py
  scout/adapter/mongo/case_events.py
  scout/adapter/mongo/hgnc.py
  scout/adapter/mongo/panel.py
  scout/adapter/mongo/variant.py
  scout/server/blueprints/variants/controllers.py
  scout/server/extensions/bionano_extension.py
  scout/server/extensions/loqus_extension.py
  scout/server/extensions/phenopacket_extension.py
  scout/utils/coordinates.py
  scout/utils/dict_utils.py
  scout/utils/ensembl_rest_clients.py
  scout/utils/gene.py
  scout/utils/scout_requests.py
  tests/server/extensions/test_loqusdb_api_extension.py
  tests/server/extensions/test_loqusdb_exe_extension.py
  tests/utils/test_dict_utils.py
  tests/utils/test_ensembl_rest_clients.py
  tests/utils/test_gene.py
  tests/utils/test_par.py
Labels: Easy, QualityOfLife, Refactor

#4342 Enable Cancer SV observations view
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/variant_details.html
Labels: Bugfix

#4347 Remove unused parameter in server/blueprints/variant/controllers/observations
  CHANGELOG.md
  scout/server/blueprints/variant/controllers.py
  scout/server/blueprints/variant/templates/variant/variant_details.html
  scout/server/blueprints/variant/views.py
  tests/server/blueprints/variant/test_variant_controllers.py
Labels: Easy

#4348 Fix archived local obs not visible on cancer variantS page
  CHANGELOG.md
  scout/server/blueprints/variants/templates/variants/components.html
Labels: Easy, Bugfix

#4351 Allow ClinVar submissions with custom API keys and allow resetting submission ID
  CHANGELOG.md
  scout/server/blueprints/clinvar/controllers.py
  scout/server/blueprints/clinvar/templates/clinvar/clinvar_submissions.html
  scout/server/blueprints/clinvar/views.py
Labels: Easy, QualityOfLife

#4355 Show user that created a ClinVar submission, when available
  CHANGELOG.md
  scout/adapter/mongo/clinvar.py
  scout/server/blueprints/clinvar/templates/clinvar/clinvar_submissions.html
  scout/server/blueprints/clinvar/views.py
Labels: Easy

#4354 Genes for orpha disease_terms are now saved as int, matching the format for omim disease_terms
  CHANGELOG.md
  scout/parse/orpha.py
  tests/parse/conftest.py
  tests/parse/test_parse_disease_terms.py
  tests/parse/test_parse_orpha.py
Labels: Easy

#4361 Associate .d4 files to individuals when loading a case via config file
  CHANGELOG.md
  scout/build/individual.py
  scout/demo/643594.config.yaml
  scout/demo/ADM1059A1.d4
  scout/demo/ADM1059A2.d4
  scout/demo/ADM1059A3.d4
  scout/models/case/case_loading_models.py
  tests/parse/test_parse_case.py
Labels: enhancement, Easy

#4362 Remove the unused no-variants param from load_case cli
  CHANGELOG.md
  scout/commands/load/case.py
Labels: Easy

#4364 Remove capital letters from descriptions of ClinVar events on case page
  CHANGELOG.md
  scout/constants/case_tags.py
Labels: Easy

#4363 Update individual's path to .d4 files for an existing case
  CHANGELOG.md
  scout/commands/update/individual.py
  tests/commands/update/test_update_individual_cmd.py
Labels: enhancement, Easy

#4370 Fix number of phenotypes and genes from case diagnoses
  CHANGELOG.md
  scout/adapter/mongo/disease_terms.py
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/templates/cases/case.html
  scout/server/blueprints/cases/templates/cases/phenotype.html
  tests/adapter/mongo/test_diagnosis_handler.py
Labels: Easy, Bugfix

#4379 Associate ClinVar variants with Orphanet conditions
  CHANGELOG.md
  scout/server/blueprints/clinvar/controllers.py
  scout/server/blueprints/clinvar/form.py
  scout/server/blueprints/clinvar/templates/clinvar/multistep_add_variant.html
Labels: Easy, Bugfix

#4377 Introduce a super-simple ClinVar multistep validation system and validate associated condition
  CHANGELOG.md
  scout/server/blueprints/clinvar/templates/clinvar/multistep_add_variant.html
Labels: Easy, QualityOfLife

#4381 Fix diseases associated to partial causatives (style, links)
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/utils.html
  scout/server/blueprints/variant/templates/variant/utils.html
Labels: Easy, Frontend
