Repository Clinical-Genomics/scout, pull requests merged in 2024-12, with the labels that each got.

#5093 Contain custom image size and add a link to show them full size in another tab
  CHANGELOG.md
  scout/demo/643594.config.yaml
  scout/demo/images/custom_images/1300x1000.jpg
  scout/demo/images/custom_images/640x480_two.jpg
  scout/server/static/custom_images.js
Labels: Frontend

#5096 Fix missing classifications in case report
  CHANGELOG.md
  scout/adapter/mongo/variant.py
Labels: Easy, Bugfix

#5098 Add a warning to not to post sensitive info on issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/other-issue.md
  CHANGELOG.md
Labels: Easy

#5103 Fix #5102 - customer id in sharing dialog
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
  scout/server/blueprints/cases/templates/cases/index.html
Labels: Easy, Frontend

#5097 Fix multigene panels count
  CHANGELOG.md
  scout/server/blueprints/variants/templates/variants/components.html
Labels: Bugfix

#5105 Fix updating gene panels via file
  CHANGELOG.md
  scout/server/blueprints/panels/controllers.py
  scout/server/blueprints/panels/templates/panels/panel.html
Labels: Bugfix

#5107 Switch to Python 3.12 in Dockerfiles and automatic tests
  .github/workflows/build_and_publish.yml
  .github/workflows/linting_and_fixing.yml
  .github/workflows/linting_only.yml
  .github/workflows/tests_and_cov.yml
  .github/workflows/validate_internal_docs_links.yml
  CHANGELOG.md
  Dockerfile
  Dockerfile-server
  scout/commands/serve.py
Labels: Easy

#5119 Fix UCSC hg38 link
  CHANGELOG.md
  scout/server/links.py
Labels: Easy, Bugfix

#5121 Truncate protein change descriptions on variant page, RefSeq transcripts panel
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/tx_overview.html
Labels: Easy, QualityOfLife, Frontend

#5120 Add ACMG VUS Bayesian score / temperature on case reports
  CHANGELOG.md
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/templates/cases/case_report.html
  scout/utils/acmg.py
Labels: Customer Request, Easy

#5131 Fix tooltips on variants not overlapping with any gene panels
  CHANGELOG.md
  scout/server/blueprints/variants/templates/variants/components.html
Labels: Easy, Bugfix

#5132 Fix #5128 - visibility of muted vaf counts, position on cancer variantS
  CHANGELOG.md
  scout/server/blueprints/variants/templates/variants/cancer-variants.html
Labels: Easy, Frontend

#5138 Refactor and follow up on #5128 fix also for SVs
  CHANGELOG.md
  scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html
  scout/server/blueprints/variants/templates/variants/cancer-variants.html
  scout/server/blueprints/variants/templates/variants/components.html
Labels: Refactor, Frontend
