Repository Clinical-Genomics/scout, pull requests merged in 2024-02, with the labels that each got.

#4386 Fix ClinVar condition IDs format (add prefix in background)
  CHANGELOG.md
  scout/constants/__init__.py
  scout/constants/clinvar.py
  scout/server/blueprints/clinvar/controllers.py
  scout/server/blueprints/clinvar/form.py
  scout/server/blueprints/clinvar/templates/clinvar/multistep_add_variant.html
  tests/server/conftest.py
Labels: Bugfix

#4268 Retrieve genes transcripts and exons using the schug library
  CHANGELOG.md
  requirements.txt
  scout/commands/download/ensembl.py
  scout/commands/load/exons.py
  scout/commands/update/genes.py
  scout/load/exon.py
  scout/load/hgnc_gene.py
  scout/load/setup.py
  scout/load/transcript.py
  scout/parse/ensembl.py
  scout/utils/ensembl_biomart_clients.py
  scout/utils/ensembl_rest_clients.py
  scout/utils/scout_requests.py
  tests/commands/download/test_download_ensembl_cmd.py
  tests/conftest.py
  tests/utils/test_ensembl_biomart_cients.py
  tests/utils/test_ensembl_rest_clients.py
  tests/utils/test_scout_requests.py
Labels: Refactor

#4407 Replace schug dependency with requests to schug web
  CHANGELOG.md
  requirements.txt
  scout/utils/ensembl_biomart_clients.py
  tests/commands/download/test_download_ensembl_cmd.py
  tests/utils/test_ensembl_biomart_cients.py
Labels: Easy, Bugfix, blocked

#4394 Rename "Clinical significance" to "Germline classification" in ClinVar variant files
  CHANGELOG.md
  scout/constants/__init__.py
  scout/constants/clinvar.py
  scout/server/blueprints/clinvar/controllers.py
  scout/server/blueprints/clinvar/form.py
  scout/server/blueprints/clinvar/templates/clinvar/clinvar_submissions.html
  scout/server/blueprints/clinvar/templates/clinvar/multistep_add_variant.html
  scout/server/blueprints/clinvar/views.py
Labels: Bugfix

#4433 Keep beacon and Matchmaker status for reuploaded cases
  CHANGELOG.md
  scout/adapter/mongo/case.py
  scout/commands/load/case.py
Labels: Easy, Bugfix

#4318 Customise institute settings to be able to display all cases with a given status
  CHANGELOG.md
  scout/adapter/mongo/case.py
  scout/adapter/mongo/institute.py
  scout/server/blueprints/institutes/controllers.py
  scout/server/blueprints/institutes/forms.py
  scout/server/blueprints/institutes/templates/overview/cases.html
  scout/server/blueprints/institutes/templates/overview/utils.html
  tests/adapter/mongo/test_case_handling.py
Labels: Customer Request

#4438 Rename Clinical Significance to Germline Classification on multistep ClinVar form
  CHANGELOG.md
  scout/server/blueprints/clinvar/templates/clinvar/multistep_add_variant.html
Labels: Easy, Frontend

#4440 Fix #4435 - add MEI element name to variant page
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/variant.html
Labels: Easy, Frontend

#4439 Changed the cases.utils.remove button x color for better visibility
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/phenotype.html
  scout/server/blueprints/cases/templates/cases/utils.html
Labels: Easy, Frontend

#4437 Fix #4436 - update GitHub Actions
  .github/workflows/build_and_publish.yml
  .github/workflows/linting_and_fixing.yml
  .github/workflows/linting_only.yml
  .github/workflows/tests_and_cov.yml
  .github/workflows/validate_internal_docs_links.yml
  CHANGELOG.md
  docs/admin-guide/containers/systemd.md
Labels: Easy

#4449 Update Decipher base urls
  CHANGELOG.md
  scout/server/links.py
Labels: Easy, Bugfix

#4441 Fix #4396 - reset default loglevel to INFO
  CHANGELOG.md
  scout/commands/base.py
  tests/commands/test_base_command.py
Labels: Easy, QualityOfLife

#4448 Parse and save MANE transcripts info when updating genes in build 38
  CHANGELOG.md
  scout/build/genes/transcript.py
  scout/models/hgnc_map.py
  scout/parse/ensembl.py
  scout/parse/hgnc.py
  tests/conftest.py
  tests/parse/test_parse_ensembl_transcripts.py
Labels: Easy

#4450 Display MANE badges on gene pages
  CHANGELOG.md
  scout/server/blueprints/genes/templates/genes/gene.html
Labels: Easy, Frontend

#4465 Display common/uncommon/rare on mei variant summary
  CHANGELOG.md
  scout/server/blueprints/variant/controllers.py
  scout/server/blueprints/variant/utils.py
Labels: Easy
