Repository Clinical-Genomics/scout, pull requests merged in 2024-05, with the labels that each got.

#4598 Display errors loading managed variants from file on relative web page
  CHANGELOG.md
  scout/build/managed_variant.py
  scout/server/blueprints/managed_variants/templates/managed_variants/managed_variants.html
  scout/server/blueprints/managed_variants/views.py
Labels: enhancement, Easy

#4595 ClinVar submission status button
  CHANGELOG.md
  scout/server/blueprints/clinvar/controllers.py
  scout/server/blueprints/clinvar/templates/clinvar/clinvar_submissions.html
  scout/server/blueprints/clinvar/views.py
  scout/server/extensions/clinvar_extension.py
  tests/server/blueprints/clinvar/test_clinvar_views.py
Labels: enhancement, Customer Request, QualityOfLife

#4602 Fix diagnoses API search crashing with empty search string
  CHANGELOG.md
  scout/server/blueprints/diagnoses/controllers.py
Labels: Easy, Bugfix

#4573 Chanjo2 integration howto
  CHANGELOG.md
  README.md
  docs/admin-guide/chanjo_coverage_integration.md
  docs/admin-guide/load-config.md
  mkdocs.yml
Labels: docs

#4600 Use latest gene panel for panel overlap in variantS, variant view and case report
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/case_report.html
  scout/server/blueprints/variant/controllers.py
  scout/server/blueprints/variant/utils.py
  scout/server/blueprints/variants/utils.py
Labels: Bugfix

#4606 Avoid chanjo2 queries when there are no genes available for stats
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
  scout/server/blueprints/panels/templates/panels/panel.html
Labels: Easy, QualityOfLife

#4608 Fix case crashing when evaluating ClinVar vars among pinned not loaded variants
  CHANGELOG.md
  scout/server/blueprints/cases/controllers.py
Labels: Easy, Bugfix

#4620 Revert installation of flask-ldapconn
  .github/workflows/tests_and_cov.yml
  CHANGELOG.md
  Dockerfile
  Dockerfile-server
  requirements.txt
  scout/__version__.py
Labels: Bugfix

#4638 Fix MT-report crash when one of the samples is not in chanjo db
  CHANGELOG.md
  scout/server/blueprints/cases/controllers.py
Labels: Easy, Bugfix

#4640 Hide mtDNA and coverage reports for WTS cases
  CHANGELOG.md
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
  scout/server/utils.py
  tests/server/test_server_utils.py
Labels: Easy

#4646 Fix #4645 - benign modifiers
  CHANGELOG.md
  scout/adapter/mongo/base.py
  scout/utils/acmg.py
  tests/utils/test_acmg.py
Labels: Bugfix

#4644 Modify OMIM-AUTO panel to include genes in both builds
  CHANGELOG.md
  scout/adapter/mongo/hgnc.py
Labels: Bugfix
