Repository Clinical-Genomics/scout, pull requests merged in 2024-08, with the labels that each got.

#4724 Update igv.js to v 3.0.1
  CHANGELOG.md
  scout/server/blueprints/alignviewers/templates/alignviewers/utils.html
Labels: Easy

#4730 Sort IGV tracks - fix #4726
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/utils.html
Labels: Easy, Frontend

#4721 Option to override the ClinVar API URL to test against ClinVar 'apitest'
  CHANGELOG.md
  scout/constants/clinvar.py
  scout/server/app.py
  scout/server/blueprints/clinvar/controllers.py
  scout/server/config.py
  scout/server/extensions/clinvar_extension.py
  tests/server/blueprints/clinvar/test_clinvar_views.py
Labels: enhancement

#4736 Update wokeignore to avoid unfixable warning
  .wokeignore
  CHANGELOG.md
Labels: Easy, QualityOfLife

#4746 Parse gnomad keys from variants annotated with echtvar
  CHANGELOG.md
  scout/parse/variant/frequency.py
  tests/parse/test_frequency.py
Labels: Easy

#4709 Display removed panels for commoners
  CHANGELOG.md
  scout/server/blueprints/panels/controllers.py
  scout/server/blueprints/panels/templates/panels/panels.html
  scout/server/blueprints/panels/views.py
Labels: Customer Request

#4747 Parse and show CoLoRSdb frequencies
  CHANGELOG.md
  scout/build/variant/variant.py
  scout/parse/variant/frequency.py
  scout/server/blueprints/variant/utils.py
  tests/parse/test_frequency.py
Labels: Easy

#4749 Fix ExAC links
  CHANGELOG.md
  scout/server/links.py
Labels: Easy, Bugfix

#4745 Load less mei variants in scout demo instance
  CHANGELOG.md
  scout/demo/643594.clinical.mei.vcf.gz
  scout/demo/643594.clinical.mei.vcf.gz.tbi
Labels: Easy, QualityOfLife

#4733 Clickable COSMIC IGV tracks
  CHANGELOG.md
  scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html
Labels: enhancement, QualityOfLife

#4719 Un-audit filter
  CHANGELOG.md
  scout/adapter/mongo/filter.py
  scout/constants/case_tags.py
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/templates/cases/case.html
  scout/server/blueprints/cases/templates/cases/case_report.html
  scout/server/blueprints/cases/templates/cases/utils.html
  scout/server/blueprints/variants/controllers.py
  scout/server/blueprints/variants/views.py
  tests/adapter/mongo/test_event_handling.py
Labels: enhancement, QualityOfLife

#4767 Show time (hours and minutes) additionally to date on comments and activity panel
  CHANGELOG.md
  scout/server/templates/utils.html
Labels: Easy, QualityOfLife

#4766 Re-style case HPO terms to have one phenotype per line
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/case.html
  scout/server/blueprints/cases/templates/cases/phenotype.html
Labels: Customer Request, Easy

#4777 Fix panelapp updating error
  CHANGELOG.md
  scout/adapter/mongo/hgnc.py
  scout/load/panel.py
Labels: Easy, Bugfix

#4779 Fix style of SNVs and SVs buttons on WTS Outliers page
  CHANGELOG.md
  scout/server/blueprints/omics_variants/templates/omics_variants/outliers.html
  scout/server/blueprints/variants/templates/variants/components.html
Labels: Easy, Frontend

#4784 Fix #4782 - explicit igv.js chr alias option
  CHANGELOG.md
  scout/constants/igv_tracks.py
  scout/server/blueprints/alignviewers/templates/alignviewers/igv_sashimi_viewer.html
  scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html
Labels: Easy, Bugfix

#4786 Update igv.js to 3.0.4.
  CHANGELOG.md
  scout/server/blueprints/alignviewers/templates/alignviewers/utils.html
Labels: enhancement, Easy
