Repository Clinical-Genomics/scout, pull requests merged in 2024-10, with the labels that each got.

#4886 More LRS SV callers
  CHANGELOG.md
  scout/constants/__init__.py
  scout/constants/variant_tags.py
Labels: Easy

#4916 Do not show ORPHA inheritance on variant page
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/gene_disease_relations.html
Labels: Customer Request, Easy

#4915 Chanjo2 MANE coverage overview
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
  scout/server/blueprints/panels/templates/panels/panel.html
Labels: enhancement, Customer Request, Easy

#4929 Fix benign moderate modifiers
  CHANGELOG.md
  scout/utils/acmg.py
  tests/utils/test_acmg.py
Labels: Bugfix

#4935 Move panel cols
  CHANGELOG.md
  scout/server/blueprints/panels/templates/panels/gene-edit.html
  scout/server/blueprints/panels/templates/panels/panel.html
Labels: Easy, QualityOfLife, Frontend

#4931 Fix updating genes in a panel with custom info
  CHANGELOG.md
  scout/adapter/mongo/panel.py
  scout/server/blueprints/panels/views.py
Labels: Bugfix

#4920 Fix #4909 - Tavtigian Bayesian point sums
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/acmg.html
  scout/server/blueprints/variant/views.py
  scout/utils/acmg.py
  tests/utils/test_acmg.py
Labels: enhancement, Customer Request

#4936 Fix pdf panel download
  CHANGELOG.md
  scout/server/blueprints/panels/controllers.py
  scout/server/blueprints/panels/templates/panels/panel_pdf_simple.html
Labels: Easy, Bugfix

#4939 Fix #4938 - show more filter categories for filterS
  CHANGELOG.md
  scout/constants/variant_tags.py
  scout/server/blueprints/institutes/controllers.py
Labels: Easy, Bugfix

#4943 Fix #4942 - respect search limit
  CHANGELOG.md
  scout/server/blueprints/institutes/controllers.py
Labels: Easy, Bugfix

#4944 Improve visibility of MME matches on dark mode
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/matchmaker.html
Labels: Easy, Frontend

#4934 Dissmisive variantS page
  CHANGELOG.md
  scout/server/blueprints/institutes/templates/overview/causatives.html
  scout/server/blueprints/institutes/templates/overview/gene_variants.html
  scout/server/blueprints/institutes/templates/overview/utils.html
  scout/server/blueprints/institutes/templates/overview/verified.html
  scout/server/blueprints/institutes/views.py
  scout/server/blueprints/omics_variants/templates/omics_variants/outliers.html
  scout/server/blueprints/omics_variants/views.py
  scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html
  scout/server/blueprints/variants/templates/variants/components.html
  scout/server/blueprints/variants/templates/variants/mei-variants.html
  scout/server/blueprints/variants/templates/variants/str-variants.html
  scout/server/blueprints/variants/templates/variants/sv-variants.html
  scout/server/blueprints/variants/templates/variants/variants.html
  scout/server/blueprints/variants/views.py
Labels: enhancement, Customer Request, QualityOfLife

#4954 Fix variant gene panel links
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/utils.html
Labels: Easy, Bugfix, Frontend

#4952 Fix downloading gene variants for genes with no symbol
  CHANGELOG.md
  scout/server/blueprints/institutes/controllers.py
Labels: Bugfix

#4961 Patch 4.90.1: fix parsing mme dates
  CHANGELOG.md
  scout/__version__.py
  scout/parse/matchmaker.py
  tests/parse/test_parse_matchmaker.py
Labels: Bugfix

#4957 On genes panel page, make more evident which genes are new after the panel is updated
  CHANGELOG.md
  scout/server/blueprints/panels/templates/panels/panel.html
  scout/server/blueprints/panels/templates/panels/panel_pdf_simple.html
Labels: Easy, QualityOfLife

#4971 Fix #4970 - empty custom images dict does not crash on load
  CHANGELOG.md
  scout/models/case/case_loading_models.py
Labels: Easy, Bugfix

#4975 Fix #4974 - crash on missing aln file for one of the inds
  CHANGELOG.md
  scout/server/utils.py
Labels: Easy, Bugfix

#4978 Fix #4977 - update IGV.js to 3.0.9
  CHANGELOG.md
  scout/server/blueprints/alignviewers/templates/alignviewers/utils.html
Labels: enhancement, Easy

#4984 /api/v1/hpo-terms handles pymongo OperationFailure errors
  CHANGELOG.md
  scout/server/blueprints/cases/views.py
Labels: Easy
