Repository Clinical-Genomics/scout, pull requests merged in 2024-11, with the labels that each got.

#4998 Fix ClinVar form to accept MedGen phenotypes
  CHANGELOG.md
  scout/server/blueprints/clinvar/templates/clinvar/multistep_add_variant.html
Labels: Easy, Bugfix

#5000 Expand ClinVar submission description section to display full info
  CHANGELOG.md
  scout/server/blueprints/clinvar/templates/clinvar/clinvar_submissions.html
Labels: Easy, QualityOfLife

#5010 Fix #5001 - Jarvik for ACMG PP1 modification
  CHANGELOG.md
  scout/constants/acmg.py
Labels: Easy, Frontend

#5009 Add MANE badges to the long list of transcripts on variant page
  CHANGELOG.md
  scout/server/blueprints/variant/controllers.py
  scout/server/blueprints/variant/templates/variant/utils.html
Labels: Easy

#5019 Display institute _id + display name on dashboard filters
  CHANGELOG.md
  scout/server/blueprints/dashboard/controllers.py
Labels: Easy, QualityOfLife, Frontend

#5022 Fix broken ClinVar submission status enquiry for all submissions after the latest
  CHANGELOG.md
  scout/server/blueprints/clinvar/templates/clinvar/clinvar_submissions.html
Labels: Easy, Bugfix, Frontend

#5040 Better layout for Consequence cell in cancer SNVs page
  CHANGELOG.md
  scout/server/blueprints/variants/templates/variants/cancer-variants.html
Labels: Easy, Frontend

#5050 Fix missing track round3
  CHANGELOG.md
  scout/server/blueprints/alignviewers/controllers.py
  scout/server/utils.py
Labels: Refactor, Bugfix

#5065 Fix stranger missing loci
  CHANGELOG.md
  scout/parse/variant/genotype.py
Labels: Easy, Bugfix

#5062 Parse and save correctly low-penetrance pathogenic and likely pathogenic ClinVar info
  CHANGELOG.md
  scout/build/variant/clnsig.py
  scout/constants/clnsig.py
  scout/parse/variant/clnsig.py
  scout/server/blueprints/variant/templates/variant/components.html
  tests/build/test_build_clnsig.py
  tests/parse/test_parse_clnsig.py
Labels: enhancement

#5061 Fix filters parse and display
  CHANGELOG.md
  scout/parse/variant/callers.py
  scout/parse/variant/variant.py
  scout/server/blueprints/variant/controllers.py
  scout/server/blueprints/variant/templates/variant/variant_details.html
  scout/server/blueprints/variant/utils.py
  scout/server/blueprints/variants/controllers.py
  scout/server/blueprints/variants/templates/variants/cancer-variants.html
  scout/server/blueprints/variants/templates/variants/utils.html
  tests/parse/test_parse_callers.py
Labels: Bugfix

#5071 Fix #5070 - WTS SNVs and SVs buttons open on new tab
  CHANGELOG.md
  scout/server/blueprints/omics_variants/templates/omics_variants/outliers.html
Labels: Easy, Bugfix, Frontend

#5077 Fixed documentation of PanelApp panels to reflect the latest changes in the command line
  CHANGELOG.md
  docs/admin-guide/panelapp_panels.md
Labels: Easy, docs

#5072 Improvements on gene panels page
  CHANGELOG.md
  scout/server/blueprints/panels/templates/panels/panels.html
Labels: enhancement, Easy, QualityOfLife, Frontend

#5089 Add more options to the variants delete command
  CHANGELOG.md
  scout/adapter/mongo/query.py
  scout/commands/delete/delete_command.py
Labels: enhancement, Easy, QualityOfLife
