Repository Clinical-Genomics/scout, pull requests merged in 2024-09, with the labels that each got.

#4806 Fix setup database command
  CHANGELOG.md
  scout/build/variant/gene.py
  scout/load/setup.py
Labels: Easy, Bugfix

#4812 Show CoLoRSdb freq in Pop Freq cell on variantS page
  CHANGELOG.md
  scout/server/blueprints/variants/templates/variants/components.html
Labels: Easy

#4722 Hovertip to gene panel names with associated genes on SV variant page
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/sv-variant.html
  scout/server/blueprints/variant/templates/variant/utils.html
  scout/server/blueprints/variant/templates/variant/variant.html
  scout/server/blueprints/variant/utils.py
Labels: Customer Request, Easy

#4799 Update case omics files
  CHANGELOG.md
  docs/admin-guide/README.md
  docs/admin-guide/load-config.md
  docs/admin-guide/loading-variants.md
  docs/admin-guide/updating-case.md
  docs/admin-guide/updating-individuals.md
  mkdocs.yml
  scout/adapter/mongo/base.py
  scout/adapter/mongo/case.py
  scout/adapter/mongo/omics_variant.py
  scout/commands/load/variants.py
  scout/commands/update/case.py
  tests/commands/load/test_load_variants_cmd.py
  tests/commands/update/test_update_case_cmd.py
Labels: enhancement

#4838 Fix broken heading anchors pointing to admin login markdown page
  CHANGELOG.md
  docs/admin-guide/login-system.md
  docs/admin-guide/setup-scout.md
Labels: Easy, Bugfix

#4841 Avoid open login redirect attacks via next
  CHANGELOG.md
  scout/server/app.py
  scout/server/blueprints/login/views.py
Labels: Easy, Bugfix

#4844 Include both creation and last modification dates in gene panels pages
  CHANGELOG.md
  scout/server/blueprints/panels/templates/panels/panel.html
  scout/server/blueprints/panels/templates/panels/panels.html
Labels: Easy, Bugfix

#4845 Move the code to collect MT copy number stats for MT report to the chanjo extension
  CHANGELOG.md
  scout/server/blueprints/cases/controllers.py
  scout/server/extensions/chanjo_extension.py
  scout/server/extensions/matchmaker_extension.py
  tests/server/blueprints/cases/test_cases_controllers.py
  tests/server/extensions/test_chanjo_extension.py
Labels: Easy, Refactor

#4830 A bit more advanced users' activity logging
  CHANGELOG.md
  docs/admin-guide/user_activity_monitoring.md
  mkdocs.yml
  scout/server/app.py
  scout/server/blueprints/login/views.py
  scout/server/blueprints/public/templates/public/index.html
  scout/server/config.py
  tests/server/blueprints/login/test_views.py
Labels: Task

#4846 Remove a duplicated panel version history list
  CHANGELOG.md
  scout/server/blueprints/panels/templates/panels/panels.html
Labels: Easy, Frontend

#4856 Igv locus make fix
  CHANGELOG.md
  scout/server/blueprints/alignviewers/controllers.py
  tests/server/blueprints/alignviewers/test_alignviewers_controllers.py
  tests/server/blueprints/alignviewers/test_alignviewers_views.py
Labels: Customer Request

#4859 Fix string pattern warnings
  CHANGELOG.md
  scout/constants/disease_parsing.py
  scout/parse/omim.py
  scout/utils/convert.py
  scout/utils/date.py
Labels: Refactor

#4865 Fix alamut link error
  CHANGELOG.md
  scout/server/links.py
Labels: Easy, Bugfix

#4871 Update igv.js chrom alias files to include alias for chrom M
  CHANGELOG.md
  scout/constants/igv_tracks.py
Labels: Bugfix

#4880 Preselect ClinVar ACMG criteria according to the variant's ACMG classification
  CHANGELOG.md
  scout/server/blueprints/clinvar/templates/clinvar/multistep_add_variant.html
Labels: Easy

#4885 Fix #4884 - enable Gens balsamic button
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/individuals_table.html
Labels: Easy

#4887 Fix search similar cases
  CHANGELOG.md
  scout/adapter/mongo/case.py
Labels: Bugfix

#4711 Cases advanced search
  CHANGELOG.md
  scout/adapter/mongo/case.py
  scout/server/blueprints/institutes/controllers.py
  scout/server/blueprints/institutes/forms.py
  scout/server/blueprints/institutes/templates/overview/cases.html
  tests/adapter/mongo/test_case_handling.py
Labels: enhancement, Customer Request

#4890 Chanjo2 report available for cases without gene panels
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
Labels: enhancement, Easy, Cancer

#4889 Fix #4888 - add RNA delivery report
  CHANGELOG.md
  docs/admin-guide/load-config.md
  scout/adapter/mongo/case.py
  scout/build/case.py
  scout/constants/case_tags.py
  scout/demo/643594.config.yaml
  scout/models/case/case_loading_models.py
  scout/server/app.py
  scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
Labels: enhancement, Easy, RNA-seq
