Repository Clinical-Genomics/scout, pull requests merged in 2024-07, with the labels that each got.

#4697 Sort select default
  CHANGELOG.md
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/templates/cases/gene_panel.html
Labels: Easy, Bugfix

#4710 REVEL score deep parsing
  CHANGELOG.md
  scout/parse/variant/variant.py
Labels: enhancement

#4715 Replace broken "remove" icon
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/case.html
  scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
  scout/server/blueprints/cases/templates/cases/utils.html
  scout/server/templates/utils.html
Labels: Easy, Bugfix, Frontend
