Repository Clinical-Genomics/scout, pull requests merged in 2025-04, with the labels that each got.

#5368 Chanjo2 gene coverage report reflects type of analyses
  CHANGELOG.md
  scout/server/extensions/chanjo2_extension.py
Labels: Easy

#5369 Clearer case panels tabs
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/gene_panel.html
  scout/server/blueprints/panels/templates/panels/panel.html
Labels: Customer Request, Easy, QualityOfLife

#5370 Respect case rank score threshold when uploading research variants
  CHANGELOG.md
  scout/commands/load/research.py
Labels: Easy

#5373 Add the documentation on how to export data using the CLI
  CHANGELOG.md
  docs/admin-guide/export.md
Labels: Easy, docs

#5367 Filter cancer SNVs by oncogenicity
  CHANGELOG.md
  scout/adapter/mongo/query.py
  scout/constants/__init__.py
  scout/constants/query_terms.py
  scout/server/blueprints/variants/forms.py
  scout/server/blueprints/variants/templates/variants/utils.html
  tests/adapter/mongo/test_query.py
Labels: enhancement, Cancer

#5382 Update PR template instructions to not stop target when deploying a test branch
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
Labels: Easy, QualityOfLife

#5377 Fix general report to show all dismissed variants (not pinned or causatives) only among the dismissed
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/case_report.html
Labels: Easy, QualityOfLife

#5391 controllers.variants tests in the app context
  CHANGELOG.md
  tests/server/blueprints/variants/test_variants_controllers.py
Labels: Bugfix

#5365 Keep phenotype-related info on case reupload with --keep-actions tag
  CHANGELOG.md
  scout/adapter/mongo/case.py
Labels: Easy, QualityOfLife

#5393 Fix step back in ClinVar multistep form
  CHANGELOG.md
  scout/server/blueprints/clinvar/templates/clinvar/multistep_add_variant.html
Labels: Easy, Bugfix, Frontend

#5397 Fix build 38 chanjo2 MT report
  CHANGELOG.md
  scout/server/blueprints/cases/controllers.py
  scout/server/extensions/chanjo2_extension.py
  scout/server/utils.py
  tests/server/extensions/test_chanjo2_extension.py
Labels: Bugfix

#5404 Truncate all compounds names on compounds popup table
  CHANGELOG.md
  scout/server/blueprints/variants/templates/variants/utils.html
Labels: Easy, QualityOfLife, Frontend

#5409 Clearer messages when loading vars
  CHANGELOG.md
  scout/adapter/mongo/variant_loader.py
  scout/commands/load/research.py
Labels: Easy

#5419 Fix matching ranked
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/components.html
  scout/server/blueprints/variant/templates/variant/sv-variant.html
  scout/server/blueprints/variants/templates/variants/indicators.html
  scout/server/static/bs_styles.css
Labels: Bugfix

#5422 Fix broken scout setup database command
  CHANGELOG.md
  scout/commands/download/ensembl.py
  scout/parse/ensembl.py
  scout/utils/ensembl_biomart_clients.py
  tests/commands/download/test_download_omim_cmd.py
Labels: Easy, Bugfix

#5421 Fix get ClinVar submissions for removed cases
  CHANGELOG.md
  scout/adapter/mongo/clinvar.py
  scout/server/blueprints/clinvar/controllers.py
  scout/server/blueprints/clinvar/templates/clinvar/clinvar_submissions.html
Labels: Bugfix

#5424 Silence refseq warnings
  CHANGELOG.md
  scout/utils/scout_requests.py
Labels: Easy, QualityOfLife
