Repository Clinical-Genomics/scout, pull requests merged in 2025-05, with the labels that each got.

#5436 Institutes by ID on PanelS page
  CHANGELOG.md
  scout/server/blueprints/panels/views.py
Labels: Easy, QualityOfLife

#5439 Simplify previous classifications badges on variantS page
  CHANGELOG.md
  scout/server/blueprints/variants/templates/variants/indicators.html
Labels: Easy, QualityOfLife, Frontend

#5440 Avoid also repetated CCV classification badges on cancer variants page
  CHANGELOG.md
  scout/server/blueprints/variants/templates/variants/cancer-variants.html
  scout/server/blueprints/variants/templates/variants/indicators.html
  scout/server/blueprints/variants/templates/variants/utils.html
Labels: Easy, Frontend

#5442 Remove ClinVar add button for unsupported MEI variants
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/utils.html
Labels: Easy, Bugfix

#5426 On ClinVar submissions form, skip collecting refseq version for non-MANE build 38 transcripts
  CHANGELOG.md
  scout/server/blueprints/clinvar/controllers.py
  scout/server/blueprints/clinvar/templates/clinvar/multistep_add_variant.html
Labels: Easy, QualityOfLife

#5453 Fix failing test
  CHANGELOG.md
  tests/adapter/mongo/test_sanger_validation.py
Labels: Easy, Bugfix, blocking

#5455 Fix #5454 - long STRs display on case page
  CHANGELOG.md
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/templates/cases/utils.html
  scout/server/blueprints/variant/controllers.py
  scout/server/blueprints/variant/utils.py
  scout/server/blueprints/variants/controllers.py
Labels: Bugfix, Frontend

#5443 Refactor and simplify code collecting case genome build
  CHANGELOG.md
  scout/server/blueprints/alignviewers/controllers.py
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/clinvar/controllers.py
  scout/server/blueprints/institutes/controllers.py
  scout/server/blueprints/omics_variants/views.py
  scout/server/blueprints/variant/controllers.py
  scout/server/blueprints/variants/controllers.py
  scout/server/blueprints/variants/views.py
  scout/server/extensions/beacon_extension.py
  scout/server/utils.py
Labels: Refactor

#5463 Remove observations when removing ClinVar variant
  CHANGELOG.md
  scout/adapter/mongo/clinvar.py
Labels: Easy, Bugfix

#5468 Fix chanjo2 full coverage check for variants without genes
  CHANGELOG.md
  scout/server/blueprints/variant/controllers.py
Labels: Easy

#5478 Clinvar links on report
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/case_report.html
Labels: Customer Request, Easy

#5479 Reuse the variant frequencies table from variant page on case reports
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/case_report.html
  scout/server/blueprints/variant/templates/variant/variant_details.html
Labels: Customer Request, Easy

#5486 Do not raise error when trying to load missing omics files
  CHANGELOG.md
  scout/adapter/mongo/omics_variant.py
  scout/adapter/mongo/variant_loader.py
Labels: Easy

#5489 Fix #5480 - UCSC link for SV breakpoint in hg38
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/utils.html
Labels: Easy, Bugfix

#5496 Fix #5494 - IGV.js genomes.json URL intermittent errors
  CHANGELOG.md
  scout/constants/igv_tracks.py
  scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html
  scout/server/blueprints/alignviewers/templates/alignviewers/utils.html
Labels: Bugfix
