Repository Clinical-Genomics/scout, pull requests merged in 2025-01, with the labels that each got.

#5157 Fix #5153 - general report ACMG temperature respects criteria term modifier
  CHANGELOG.md
  scout/server/blueprints/cases/controllers.py
Labels: Bugfix

#5158 Fix odd hgnc gene inheritance
  CHANGELOG.md
  scout/parse/omim.py
  scout/utils/link.py
  uv.lock
Labels: Bugfix

#5162 Clearer links to Richards 2015
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/components.html
Labels: Easy

#5165 Parse HGNC IDs directly from PanelApp when updating PanelApp panels
  CHANGELOG.md
  scout/adapter/mongo/hgnc.py
  scout/load/panelapp.py
  scout/parse/panelapp.py
Labels: Bugfix

#5168 Fix loading of PanelApp panels
  CHANGELOG.md
  scout/load/panelapp.py
Labels: Easy, Bugfix

#5169 Reduced number of research MEI variants present in the demo case
  CHANGELOG.md
  scout/demo/643594.research.mei.vcf.gz
  scout/demo/643594.research.mei.vcf.gz.tbi
Labels: Easy, QualityOfLife

#5172 Fix save PanelApp inheritance models
  CHANGELOG.md
  scout/constants/gene_tags.py
  scout/parse/panelapp.py
Labels: Easy, Bugfix

#5174 Fix query by coordinates - start coordinate must be >=1
  CHANGELOG.md
  scout/adapter/mongo/managed_variant.py
  scout/adapter/mongo/query.py
  scout/server/blueprints/managed_variants/forms.py
  scout/server/blueprints/managed_variants/templates/managed_variants/managed_variants.html
  scout/server/blueprints/variants/forms.py
Labels: Easy, Bugfix

#5181 update release docs
  CHANGELOG.md
  RELEASE.md
Labels: docs

#5183 Truncate long HGVS descriptions on cancer SNVS and SNV pages
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/cancer-variant.html
  scout/server/blueprints/variants/templates/variants/cancer-variants.html
Labels: Easy, QualityOfLife

#5185 Skip calling rank function for the demo case without ranking
  CHANGELOG.md
  docs/admin-guide/loading-case.md
  scout/demo/cancer.load_config.yaml
Labels: Easy

#5190 Case status on loading
  CHANGELOG.md
  docs/admin-guide/load-config.md
  scout/build/case.py
  scout/demo/rnafusion.load_config.yaml
  scout/models/case/case_loading_models.py
  scout/parse/case.py
Labels: enhancement, Easy

#5191 Add severity predictions and functional annotation on case report for SNVs and cancer SNVs
  CHANGELOG.md
  scout/server/app.py
  scout/server/blueprints/cases/templates/cases/case_report.html
  scout/server/blueprints/variant/templates/variant/variant_details.html
  scout/server/links.py
Labels: enhancement, Customer Request

#5192 Display version of scout used when loading a case on case page and general report
  CHANGELOG.md
  scout/adapter/mongo/case.py
  scout/build/case.py
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/templates/cases/case_report.html
  scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html
Labels: enhancement, QualityOfLife

#5195 Fix #5194 - display STR variant filter status on variantS page
  CHANGELOG.md
  scout/server/blueprints/variants/templates/variants/str-variants.html
Labels: enhancement, Easy

#5200 Discontinue ClinVar submissions via CSV files
  CHANGELOG.md
  scout/server/blueprints/clinvar/templates/clinvar/clinvar_submissions.html
  scout/server/blueprints/clinvar/views.py
  tests/server/blueprints/clinvar/test_clinvar_views.py
Labels: Easy, Task

#5188 More acmg conflicts warnings
  CHANGELOG.md
  scout/constants/acmg.py
  scout/utils/acmg.py
Labels: Easy, Refactor
