Repository Clinical-Genomics/scout, pull requests merged in 2025-02, with the labels that each got.

#5213 Sort WTS outliers by p_value, Δψ, ψ value, zscore or l2fc
  CHANGELOG.md
  scout/adapter/mongo/omics_variant.py
  scout/server/blueprints/omics_variants/templates/omics_variants/outliers.html
  scout/server/blueprints/variants/forms.py
Labels: enhancement, Customer Request, Easy

#5218 Fix parsing of entire Ensembl documents - including MT-TP gene
  CHANGELOG.md
  scout/utils/ensembl_biomart_clients.py
Labels: Easy, Bugfix

#5209 pLI scores on SNV and cancer SNV pages
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/cancer-variant.html
  scout/server/blueprints/variant/templates/variant/variant.html
  scout/server/blueprints/variant/utils.py
Labels: Customer Request, QualityOfLife

#5225 Set case as research case if it contains any type of research variants
  CHANGELOG.md
  scout/adapter/mongo/case.py
  scout/commands/load/variants.py
Labels: Easy

#5234 Refactor variants loading prio
  CHANGELOG.md
  scout/adapter/mongo/case.py
  scout/adapter/mongo/omics_variant.py
  scout/adapter/mongo/variant_loader.py
  scout/commands/load/research.py
  scout/commands/load/variants.py
  scout/constants/__init__.py
  scout/constants/file_types.py
  scout/demo/643594.config.yaml
  scout/load/all.py
  scout/models/case/case_loading_models.py
  scout/utils/sort.py
  tests/utils/test_sort.py
Labels: QualityOfLife, Refactor

#5243 Fix #5237 - enable HPO searches on WTS outlier page
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/gene_panel.html
  scout/server/blueprints/omics_variants/views.py
Labels: Easy, Bugfix

#5244 Variants filter by size
  CHANGELOG.md
  scout/adapter/mongo/query.py
  scout/server/blueprints/variants/forms.py
  scout/server/blueprints/variants/templates/variants/utils.html
Labels: enhancement, Easy

#5006 Group the 3 ClinVar filters together
  CHANGELOG.md
  scout/adapter/mongo/query.py
  scout/constants/query_terms.py
  tests/adapter/mongo/test_query.py
Labels: Refactor, Bugfix

#5251 Fix #5250 - update IGV.js to 3.2.0
  CHANGELOG.md
  scout/constants/igv_tracks.py
  scout/server/blueprints/alignviewers/templates/alignviewers/utils.html
Labels: Easy, Bugfix

#5257 Ordered filters
  CHANGELOG.md
  scout/adapter/mongo/filter.py
  scout/server/blueprints/omics_variants/views.py
  scout/server/blueprints/variants/controllers.py
  scout/server/blueprints/variants/views.py
Labels: Easy, QualityOfLife

#5254 Institute-level soft filters for variants
  CHANGELOG.md
  scout/adapter/mongo/institute.py
  scout/adapter/mongo/query.py
  scout/constants/query_terms.py
  scout/server/blueprints/institutes/controllers.py
  scout/server/blueprints/institutes/forms.py
  scout/server/blueprints/institutes/templates/overview/institute_settings.html
  scout/server/blueprints/institutes/templates/overview/utils.html
  scout/server/blueprints/variants/controllers.py
  scout/server/blueprints/variants/forms.py
  scout/server/blueprints/variants/templates/variants/utils.html
  scout/server/blueprints/variants/views.py
  tests/adapter/mongo/test_query.py
  tests/server/blueprints/institutes/test_institute_views.py
Labels: enhancement, Customer Request

#5259 Fix #5258 - stop clinical filter HPO when dynamic gene panel is emptied
  CHANGELOG.md
  scout/server/blueprints/cases/controllers.py
  scout/server/blueprints/cases/templates/cases/gene_panel.html
  scout/server/blueprints/cases/views.py
  scout/server/blueprints/omics_variants/views.py
  scout/server/blueprints/variants/controllers.py
  scout/server/blueprints/variants/views.py
Labels: Bugfix

#5264 Prioritise ClinVar checkbox
  CHANGELOG.md
  scout/adapter/mongo/query.py
  scout/constants/filters.py
  scout/server/blueprints/variants/controllers.py
  scout/server/blueprints/variants/forms.py
  scout/server/blueprints/variants/templates/variants/utils.html
  tests/adapter/mongo/test_query.py
Labels: Bugfix

#5271 Hide soft clips in IGV for wes and panel samples
  CHANGELOG.md
  scout/server/blueprints/alignviewers/controllers.py
  scout/server/blueprints/alignviewers/templates/alignviewers/igv_viewer.html
  scout/server/utils.py
Labels: Easy
