Repository Clinical-Genomics/scout, pull requests merged in 2025-07, with the labels that each got.

#5546 Fix #5545 - REVEL and SpliceAI missing dash color
  CHANGELOG.md
  scout/server/blueprints/variant/templates/variant/variant_details.html
Labels: Easy, Bugfix

#5539 Add institute selection to Search SNVs & SVs page
  CHANGELOG.md
  scout/server/blueprints/institutes/forms.py
  scout/server/blueprints/institutes/templates/overview/gene_variants.html
  scout/server/blueprints/institutes/views.py
  tests/server/blueprints/institutes/test_institute_views.py
Labels: enhancement, Customer Request

#5504 Do not reorder Sanger on case re-upload
  CHANGELOG.md
  scout/adapter/mongo/case.py
  tests/commands/load/test_load_variants_cmd.py
Labels: Easy, QualityOfLife, Bugfix

#5552 Str read support
  CHANGELOG.md
  scout/parse/variant/genotype.py
  tests/parse/test_parse_genotype.py
Labels: enhancement, Bugfix, LRS

#5510 Submit oncogenicity classifications to ClinVar directly
  CHANGELOG.md
  scout/adapter/mongo/clinvar.py
  scout/server/blueprints/clinvar/controllers.py
  scout/server/blueprints/clinvar/templates/clinvar/clinvar_onc_submissions.html
  scout/server/blueprints/clinvar/views.py
  scout/server/extensions/clinvar_extension.py
Labels: enhancement, Easy

#5561 Clinvar sidebar margin
  CHANGELOG.md
  scout/server/blueprints/institutes/templates/overview/institute_sidebar.html
Labels: Easy

#5571 Always display number of available/displayed variants on variantS pages
  CHANGELOG.md
  scout/server/blueprints/omics_variants/templates/omics_variants/outliers.html
  scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html
  scout/server/blueprints/variants/templates/variants/cancer-variants.html
  scout/server/blueprints/variants/templates/variants/mei-variants.html
  scout/server/blueprints/variants/templates/variants/str-variants.html
  scout/server/blueprints/variants/templates/variants/sv-variants.html
  scout/server/blueprints/variants/templates/variants/utils.html
  scout/server/blueprints/variants/templates/variants/variants.html
Labels: Easy, Frontend

#5577 Fix downloaded panels names sanitization
  CHANGELOG.md
  scout/server/blueprints/panels/controllers.py
Labels: Easy, Bugfix

#5584 Sort institute multiselect alphabetically by display name on 'Search SNVs & SVs' page
  CHANGELOG.md
  scout/server/blueprints/institutes/views.py
Labels: Easy, QualityOfLife
