Repository Clinical-Genomics/scout, pull requests merged in 2025-08, with the labels that each got.

#5592 Fix deprecated flask login
  CHANGELOG.md
  pyproject.toml
  uv.lock
Labels: Easy

#5600 Fix links to SNVs and SVs from SMN page
  CHANGELOG.md
  scout/server/blueprints/cases/templates/cases/case_sma.html
  scout/server/blueprints/omics_variants/templates/omics_variants/outliers.html
  scout/server/blueprints/variants/templates/variants/cancer-sv-variants.html
  scout/server/blueprints/variants/templates/variants/fusion-variants.html
  scout/server/blueprints/variants/templates/variants/mei-variants.html
  scout/server/blueprints/variants/templates/variants/sv-variants.html
  scout/server/blueprints/variants/templates/variants/variants.html
Labels: Easy, QualityOfLife

#5634 Fix #5586 - TRGT_ID loci gets late genes.hgnc_symbol population, and hence strange reload behaviour
  CHANGELOG.md
  scout/server/blueprints/variants/controllers.py
  scout/server/blueprints/variants/templates/variants/str-variants.html
Labels: Bugfix

#5639 New "P-value", "Abs log₂FC" and "abs ΔΨ" WTS filters options
  CHANGELOG.md
  scout/adapter/mongo/query.py
  scout/constants/query_terms.py
  scout/server/blueprints/omics_variants/templates/omics_variants/outliers.html
  scout/server/blueprints/variants/forms.py
  tests/adapter/mongo/test_query.py
Labels: enhancement, Customer Request

#5644 Fix Dockerfiles to remove package metadata after installation
  CHANGELOG.md
  Dockerfile
  Dockerfile-server
Labels: Easy

#5638 Centralised config loader for cli and web app
  CHANGELOG.md
  scout/commands/base.py
  scout/server/app.py
  scout/utils/config.py
  tests/commands/test_base_command.py
Labels: Refactor

#5654 Clearer export causatives command
  CHANGELOG.md
  docs/admin-guide/export.md
  scout/commands/export/export_command.py
  scout/commands/export/variant.py
  scout/export/variant.py
  tests/commands/export/test_export_causatives_verified_cmd.py
Labels: Easy, QualityOfLife
